
#if (ORIG_DTYPE_QUERY == DT_FLOAT16) && (ORIG_DTYPE_KEY == DT_FLOAT16)
#if TILING_KEY_VAR == RIGHT_KEY
    INVOKE();
#endif
#elif (ORIG_DTYPE_QUERY == DT_BF16)
#if TILING_KEY_VAR == BF16_KEY
    INVOKE();
#endif
#endif
