ASCENDC_TPL_ARGS_DECL(
  ToyOp,
  ASCENDC_TPL_BOOL_DECL(IsEmpty, 0, 1),
  ASCENDC_TPL_UINT_DECL(Split, ASCENDC_TPL_3_BW, UI_LIST, 0, 1, 5),
  ASCENDC_TPL_BOOL_DECL(Flag, 0, 1)
);
ASCENDC_TPL_ARGS_SEL(
  ASCENDC_TPL_BOOL_SEL(IsEmpty, 0),
  ASCENDC_TPL_UINT_SEL(Split, UI_LIST, 0, 1),
  ASCENDC_TPL_BOOL_SEL(Flag, 0, 1)
);
ASCENDC_TPL_ARGS_SEL(
  ASCENDC_TPL_BOOL_SEL(IsEmpty, 1),
  ASCENDC_TPL_UINT_SEL(Split, UI_LIST, 5),
  ASCENDC_TPL_BOOL_SEL(Flag, 0)
);
