ASCENDC_TPL_ARGS_DECL(_synthetic_toy,
    ASCENDC_TPL_UINT_DECL(A, ASCENDC_TPL_3_BW, ASCENDC_TPL_UI_LIST, 0, 1, 2),
)
ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(A, ASCENDC_TPL_UI_LIST, 0, 1, 2),
)
