ASCENDC_TPL_ARGS_DECL(Toy,
  ASCENDC_TPL_UINT_DECL(InputDType, ASCENDC_TPL_3_BW, ASCENDC_TPL_UI_LIST, 0, 1),
  ASCENDC_TPL_BOOL_DECL(IsTnd, 0, 1),
  ASCENDC_TPL_BOOL_DECL(IsRope, 0, 1));
ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
  ASCENDC_TPL_UINT_SEL(InputDType, ASCENDC_TPL_UI_LIST, 0, 1),
  ASCENDC_TPL_BOOL_SEL(IsTnd, 0, 1),
  ASCENDC_TPL_BOOL_SEL(IsRope, 0, 1)));
