"""CE workflow specs: /ce-plan, /ce-apply, /ce-review, /handoff.

Formal CE products are markdown only ({slug}_plan.md, session_handoff.md).
No CE yaml. TG reads the plan markdown or review dialogue itself.
"""

from __future__ import annotations

from typing import Any, Callable


def attach_ce_workflows(
    workflows: dict[str, dict[str, Any]],
    *,
    _act: Callable[..., dict[str, Any]],
    _st: Callable[..., dict[str, str]],
    _tr: Callable[..., dict[str, Any]],
) -> None:
    workflows.update(_build(_act=_act, _st=_st, _tr=_tr))


def _build(
    *,
    _act: Callable[..., dict[str, Any]],
    _st: Callable[..., dict[str, str]],
    _tr: Callable[..., dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    return {
    "ce-plan": {
        "slash": "/ce-plan",
        "engine": "ce",
        "cognitive_skill_id": "code-engineering",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "occupancy": "exclusive",
        "occupancy_group": "ce-plan",
        "entry_state": "kb_ready",
        "terminal_ready_states": ["confirm"],
        "retry_budget": 3,
        "states": [
            _st("kb_ready", "校验知识库"),
            _st("grill", "问清需求"),
            _st("draft", "写出需求计划"),
            _st("confirm", "确认去 apply 或继续改计划"),
        ],
        "transitions": [
            _tr("kb_ready", "grill"),
            _tr("grill", "draft"),
            _tr("draft", "confirm"),
            _tr("grill", "grill", kind="rework", reason_codes=["GRILL_OPEN"]),
            _tr("confirm", "grill", kind="rework", reason_codes=["GRILL_OPEN"]),
            _tr("confirm", "draft", kind="rework", reason_codes=["rework"]),
        ],
        "phase_gates": {"kb_ready": ["kb_ready"]},
        "complete_gates": ["kb_ready"],
        "pipelines": {
            "kb_ready": ["kb_check"],
            "grill": ["intent_grill", "grill_promote", "grill_confirm"],
            "draft": ["plan_draft"],
            "confirm": ["human_confirm"],
        },
        "actions": [
            _act(
                "kb_check",
                label_zh="校验 CodeMap 就绪",
                phases=["kb_ready"],
                workflow_id="ce-plan",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                pre_gates=["kb_ready"],
                capability_ids=["kb-query"],
                output_contract_id="ce-kb-check-v1",
            ),
            _act(
                "intent_grill",
                label_zh="问清变更需求",
                phases=["grill"],
                workflow_id="ce-plan",
                agent_id="ce-analyst",
                role_id="producer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                action_method_id="code-engineering/ce-intent-grill",
                task_prompt_id="ce/intent-grill",
                context_profile_id="ce-plan-intent-grill",
                output_contract_id="intent-grill-v1",
                output_mode="staged",
                staging_contract_id="intent-grill-staging-v1",
                merge_action_id="grill_promote",
            ),
            _act(
                "grill_promote",
                label_zh="确认 grill 草稿存在",
                phases=["grill"],
                workflow_id="ce-plan",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="intent-grill-v1",
            ),
            _act(
                "grill_confirm",
                label_zh="确认需求已问清或继续问",
                phases=["grill"],
                workflow_id="ce-plan",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                human_interaction="confirm",
                capability_ids=[],
                task_prompt_id=None,
                context_profile_id="ce-plan-grill-confirm",
                output_contract_id="ce-plan-grilled-v1",
            ),
            _act(
                "plan_draft",
                label_zh="写出 {slug}_plan.md",
                phases=["draft"],
                workflow_id="ce-plan",
                agent_id="ce-analyst",
                role_id="producer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                action_method_id="code-engineering/ce-plan-draft",
                task_prompt_id="ce/plan-draft",
                context_profile_id="ce-plan-draft",
                output_contract_id="ce-plan-v1",
            ),
            _act(
                "human_confirm",
                label_zh="确认计划并选择下一步",
                phases=["confirm"],
                workflow_id="ce-plan",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                human_interaction="confirm",
                capability_ids=[],
                task_prompt_id=None,
                context_profile_id="ce-plan-human-confirm",
                output_contract_id="ce-plan-confirmed-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-ce-engine", "role": "deterministic_engine"},
            {"id": "ce-analyst", "role": "producer"},
            {"id": "ascendc-pilot", "role": "controller"},
        ],
        "static_obligations": [],
        "dynamic_obligation_sources": [],
        "write_roots": ["ce/plan", "runs", "context"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": [],
            "reinit_preserve": ["uo", "tg", "ce/plan"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["kb_ready", "grill", "draft", "confirm"],
        "gates": ["kb_ready"],
    },
    "ce-apply": {
        "slash": "/ce-apply",
        "engine": "ce",
        "cognitive_skill_id": "code-engineering",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "occupancy": "exclusive",
        "occupancy_group": "ce-apply",
        "entry_state": "gate",
        "terminal_ready_states": ["report"],
        "retry_budget": 3,
        "states": [
            _st("gate", "校验当前计划 todo"),
            _st("patch", "按 todo 改源码"),
            _st("guard", "校验改动落在计划文件内"),
            _st("refresh", "刷新 CodeMap"),
            _st("report", "汇报改动并选择下一步"),
        ],
        "transitions": [
            _tr("gate", "patch"),
            _tr("patch", "guard"),
            _tr("guard", "refresh"),
            _tr("refresh", "report"),
            _tr("guard", "patch", kind="rework", reason_codes=["PATCH_OUT_OF_ANCHORS"]),
        ],
        "phase_gates": {},
        "complete_gates": [],
        "pipelines": {
            "gate": ["apply_gate"],
            "patch": ["patch"],
            "guard": ["patch_guard"],
            "refresh": ["codemap_refresh"],
            "report": ["apply_report"],
        },
        "actions": [
            _act(
                "apply_gate",
                label_zh="校验当前计划有未完成 todo",
                phases=["gate"],
                workflow_id="ce-apply",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="apply-gate-v1",
            ),
            _act(
                "patch",
                label_zh="按计划 todo 改算子源码",
                phases=["patch"],
                workflow_id="ce-apply",
                agent_id="ce-applier",
                role_id="producer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                action_method_id="code-engineering/ce-apply",
                task_prompt_id="ce/apply",
                context_profile_id="ce-apply-patch",
                output_contract_id="apply-patch-v1",
            ),
            _act(
                "patch_guard",
                label_zh="校验改动落在计划声明的文件内",
                phases=["guard"],
                workflow_id="ce-apply",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="apply-patch-guard-v1",
            ),
            _act(
                "codemap_refresh",
                label_zh="确定性刷新 CodeMap",
                phases=["refresh"],
                workflow_id="ce-apply",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="codemap-refresh-v1",
            ),
            _act(
                "apply_report",
                label_zh="汇报改动并选择审查或测试",
                phases=["report"],
                workflow_id="ce-apply",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                human_interaction="confirm",
                capability_ids=[],
                task_prompt_id=None,
                context_profile_id="ce-apply-report",
                output_contract_id="apply-report-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-ce-engine", "role": "deterministic_engine"},
            {"id": "ce-applier", "role": "producer"},
            {"id": "ascendc-pilot", "role": "controller"},
        ],
        "static_obligations": [],
        "dynamic_obligation_sources": [],
        "write_roots": ["op_host", "op_kernel", "common", "test_script", "ce/plan", "uo", "runs", "context"],
        "reset_policy": {
            "reinit_delete": [],
            "reinit_preserve": ["uo", "tg", "ce/plan"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["gate", "patch", "guard", "refresh", "report"],
        "gates": [],
    },
    "ce-review": {
        "slash": "/ce-review",
        "engine": "ce",
        "cognitive_skill_id": "code-review",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "occupancy": "shared",
        "occupancy_group": "",
        "entry_state": "scope",
        "terminal_ready_states": ["summary"],
        "retry_budget": 3,
        "states": [
            _st("scope", "取代码改动"),
            _st("review", "双轴审查"),
            _st("summary", "建议修改或建议测试"),
        ],
        "transitions": [
            _tr("scope", "review"),
            _tr("review", "summary"),
        ],
        "phase_gates": {"scope": ["kb_ready", "context_pack"]},
        "complete_gates": ["kb_ready", "context_pack"],
        "pipelines": {
            "scope": ["change_capture"],
            "review": ["code_review"],
            "summary": ["review_report"],
        },
        "actions": [
            _act(
                "change_capture",
                label_zh="内存捕获 git/PR diff",
                phases=["scope"],
                workflow_id="ce-review",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="review-capture-v1",
                consumes_state=["pr_url"],
            ),
            _act(
                "code_review",
                label_zh="代码审查",
                phases=["review"],
                workflow_id="ce-review",
                agent_id="ce-reviewer",
                role_id="readonly_reviewer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                action_method_id="code-review/standalone-review",
                task_prompt_id="ce/standalone-review",
                context_profile_id="ce-review-code-review",
                output_contract_id="code-review-v1",
                pre_gates=["kb_ready", "context_pack"],
            ),
            _act(
                "review_report",
                label_zh="建议修改或建议测试",
                phases=["summary"],
                workflow_id="ce-review",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                human_interaction="confirm",
                capability_ids=[],
                task_prompt_id=None,
                context_profile_id="ce-review-report",
                output_contract_id="review-report-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-ce-engine", "role": "deterministic_engine"},
            {"id": "ce-reviewer", "role": "readonly_reviewer"},
            {"id": "ascendc-pilot", "role": "controller"},
        ],
        "static_obligations": [{"id": "kb_ready", "label_zh": "KB 就绪"}],
        "dynamic_obligation_sources": [],
        "write_roots": ["runs", "context"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": [],
            "reinit_preserve": ["uo", "tg", "ce"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["scope", "review", "summary"],
        "gates": ["kb_ready", "context_pack"],
    },
    "handoff": {
        "slash": "/handoff",
        "engine": "ce",
        "cognitive_skill_id": "code-engineering",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "occupancy": "shared",
        "occupancy_group": "",
        "entry_state": "session",
        "terminal_ready_states": ["session"],
        "retry_budget": 3,
        "states": [
            _st("session", "写会话交接总结"),
        ],
        "transitions": [],
        "phase_gates": {},
        "complete_gates": [],
        "pipelines": {
            "session": ["session_handoff"],
        },
        "actions": [
            _act(
                "session_handoff",
                label_zh="写会话交接总结",
                phases=["session"],
                workflow_id="handoff",
                agent_id="ce-analyst",
                role_id="producer",
                capability_ids=["kb-query"],
                action_method_id="code-engineering/session-handoff",
                task_prompt_id="ce/handoff",
                context_profile_id="handoff-session",
                output_contract_id="session-handoff-v1",
            ),
        ],
        "agents": [
            {"id": "ce-analyst", "role": "producer"},
            {"id": "ascendc-pilot", "role": "controller"},
        ],
        "static_obligations": [],
        "dynamic_obligation_sources": [],
        "write_roots": ["session_handoff.md", "runs", "context"],
        "reset_policy": {
            "reinit_delete": [],
            "reinit_preserve": ["uo", "tg", "ce"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["session"],
        "gates": [],
    },
    }
