"""Reserved Harness workflows: NL intake + change impact / test_scope.

Not in list_user_workflows(), no slash. ``auto`` is an alias of goal-intake.
"""

from __future__ import annotations

from typing import Any, Callable


def attach_goal_workflows(
    workflows: dict[str, dict[str, Any]],
    *,
    _act: Callable[..., dict[str, Any]],
    _st: Callable[..., dict[str, str]],
    _tr: Callable[..., dict[str, Any]],
) -> None:
    workflows.update(_build(_act=_act, _st=_st, _tr=_tr))


def _build(
    *,
    _act: Callable[..., dict[str, Any]],
    _st: Callable[..., dict[str, str]],
    _tr: Callable[..., dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    parse_caps = ["action-scratch"]
    impact_caps = ["kb-query", "source-navigation", "source-reading", "action-scratch"]
    return {
        "auto": {
            "alias_of": "goal-intake",
            "reserved": True,
            "occupancy": "shared",
        },
        "goal-intake": {
            "slash": "",
            "reserved": True,
            "engine": "goal",
            "cognitive_skill_id": "testcase-generation",
            "requires_project": False,
            "requires_architecture": False,
            "requires_uo_product": False,
            "occupancy": "shared",
            "occupancy_group": "",
            "entry_state": "parse",
            "terminal_ready_states": ["promote"],
            "retry_budget": 3,
            "states": [
                _st("parse", "理解用户目标"),
                _st("promote", "编制任务计划"),
            ],
            "transitions": [
                _tr("parse", "promote"),
                _tr("promote", "parse", kind="rework", reason_codes=["INTENT_INVALID"]),
            ],
            "phase_gates": {"parse": [], "promote": []},
            "pipelines": {
                "parse": ["parse_intent"],
                "promote": ["intent_promote"],
            },
            "complete_gates": [],
            "actions": [
                _act(
                    "parse_intent",
                    label_zh="理解用户原文要做哪些事",
                    phases=["parse"],
                    workflow_id="goal-intake",
                    agent_id="tg-analyst",
                    role_id="producer",
                    capability_ids=parse_caps,
                    action_method_id="testcase-generation/parse-intent",
                    task_prompt_id="tg/parse-intent",
                    context_profile_id="goal-intake-parse-intent",
                    output_contract_id="intent-promoted-v1",
                    output_mode="staged",
                    staging_contract_id="intent-staging-v1",
                    merge_action_id="intent_promote",
                    consumes_state=["intent"],
                ),
                _act(
                    "intent_promote",
                    label_zh="校验意图并编制任务计划",
                    phases=["promote"],
                    workflow_id="goal-intake",
                    agent_id="deterministic-tg-engine",
                    role_id="deterministic_engine",
                    execution_mode="deterministic",
                    capability_ids=[],
                    task_prompt_id=None,
                    output_contract_id="intent-promoted-v1",
                    consumes_state=["intent"],
                ),
            ],
            "agents": [
                {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
                {"id": "tg-analyst", "role": "producer"},
                {"id": "ascendc-pilot", "role": "controller"},
            ],
            "static_obligations": [],
            "dynamic_obligation_sources": [],
            "write_roots": ["runs", "state", "context"],
            "reset_policy": {
                "reinit_delete": [],
                "reinit_preserve": ["uo", "tg", "ce"],
                "reinit_wipe_runs": "current",
                "continue_scrub": "from_contracts",
            },
            "phases": ["parse", "promote"],
            "gates": [],
        },
        "goal-impact": {
            "slash": "",
            "reserved": True,
            "engine": "goal",
            "cognitive_skill_id": "testcase-generation",
            "requires_project": False,
            "requires_architecture": False,
            "requires_uo_product": False,
            "occupancy": "shared",
            "occupancy_group": "",
            "entry_state": "impact",
            "terminal_ready_states": ["scope"],
            "retry_budget": 3,
            "states": [
                _st("impact", "分析改动影响"),
                _st("obligations", "推导测试义务"),
                _st("scope", "确定测试范围"),
            ],
            "transitions": [
                _tr("impact", "obligations"),
                _tr("obligations", "scope"),
                _tr("impact", "impact", kind="rework", reason_codes=["IMPACT_INVALID"]),
                _tr("obligations", "impact", kind="rework", reason_codes=["OBLIGATION_INVALID"]),
            ],
            "phase_gates": {"impact": [], "obligations": [], "scope": []},
            "pipelines": {
                "impact": ["change_impact", "impact_promote"],
                "obligations": ["derive_obligations", "obligations_promote"],
                "scope": ["test_scope"],
            },
            "complete_gates": [],
            "actions": [
                _act(
                    "change_impact",
                    label_zh="分析改动影响（仅写 staging）",
                    phases=["impact"],
                    workflow_id="goal-impact",
                    agent_id="tg-analyst",
                    role_id="producer",
                    capability_ids=impact_caps,
                    action_method_id="testcase-generation/change-impact",
                    task_prompt_id="tg/change-impact",
                    context_profile_id="goal-impact-change-impact",
                    output_contract_id="change-impact-v1",
                    output_mode="staged",
                    staging_contract_id="change-impact-staging-v1",
                    merge_action_id="impact_promote",
                ),
                _act(
                    "impact_promote",
                    label_zh="校验并写入改动影响",
                    phases=["impact"],
                    workflow_id="goal-impact",
                    agent_id="deterministic-tg-engine",
                    role_id="deterministic_engine",
                    execution_mode="deterministic",
                    capability_ids=[],
                    task_prompt_id=None,
                    output_contract_id="change-impact-v1",
                ),
                _act(
                    "derive_obligations",
                    label_zh="推导测试义务（仅写 staging）",
                    phases=["obligations"],
                    workflow_id="goal-impact",
                    agent_id="tg-analyst",
                    role_id="producer",
                    capability_ids=impact_caps,
                    action_method_id="testcase-generation/change-obligations",
                    task_prompt_id="tg/change-obligations",
                    context_profile_id="goal-impact-change-obligations",
                    output_contract_id="change-obligations-v1",
                    output_mode="staged",
                    staging_contract_id="change-obligations-staging-v1",
                    merge_action_id="obligations_promote",
                ),
                _act(
                    "obligations_promote",
                    label_zh="校验并写入测试义务",
                    phases=["obligations"],
                    workflow_id="goal-impact",
                    agent_id="deterministic-tg-engine",
                    role_id="deterministic_engine",
                    execution_mode="deterministic",
                    capability_ids=[],
                    task_prompt_id=None,
                    output_contract_id="change-obligations-v1",
                ),
                _act(
                    "test_scope",
                    label_zh="确定测试范围",
                    phases=["scope"],
                    workflow_id="goal-impact",
                    agent_id="ascendc-pilot",
                    role_id="controller",
                    execution_mode="primary_interactive",
                    human_interaction="confirm",
                    capability_ids=[],
                    task_prompt_id=None,
                    context_profile_id="goal-impact-test-scope",
                    output_contract_id="test-scope-v1",
                ),
            ],
            "agents": [
                {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
                {"id": "tg-analyst", "role": "producer"},
                {"id": "ascendc-pilot", "role": "controller"},
            ],
            "static_obligations": [],
            "dynamic_obligation_sources": [],
            "write_roots": ["runs", "state", "context"],
            "reset_policy": {
                "reinit_delete": [],
                "reinit_preserve": ["uo", "tg", "ce"],
                "reinit_wipe_runs": "current",
                "continue_scrub": "from_contracts",
            },
            "phases": ["impact", "obligations", "scope"],
            "gates": [],
        },
    }
