"""Concrete workflow specs (English ids + Chinese labels)."""

from __future__ import annotations

from typing import Any

# Shared stable policies composed into every semantic / engine action.
DEFAULT_POLICY_IDS: list[str] = [
    "source-authority",
    "code-access",
    "evidence",
    "language",
    "pilot-control",
    "output-quality",
]

# Optional global capabilities merged into every action (prepended, de-duped).
# Keep empty unless a capability is truly universal; prefer per-action lists.
DEFAULT_CAPABILITY_IDS: list[str] = []


def _merge_capability_ids(capability_ids: list[str] | None) -> list[str]:
    """Merge DEFAULT_CAPABILITY_IDS with per-action ids (defaults first, de-duped)."""
    merged: list[str] = []
    for cid in list(DEFAULT_CAPABILITY_IDS) + list(capability_ids or []):
        if cid and cid not in merged:
            merged.append(cid)
    return merged


def _st(sid: str, label_zh: str) -> dict[str, str]:
    return {"id": sid, "label_zh": label_zh}


def _tr(frm: str, to: str, *, kind: str = "forward", reason_codes: list[str] | None = None) -> dict[str, Any]:
    row: dict[str, Any] = {"from": frm, "to": to, "kind": kind}
    if reason_codes:
        row["reason_codes"] = reason_codes
    return row


def _act(
    action_id: str,
    *,
    label_zh: str,
    phases: list[str],
    workflow_id: str,
    checker_required: bool = True,
    referee_required: bool = False,
    gates: list[str] | None = None,
    agent_id: str | None = None,
    role_id: str | None = None,
    execution_mode: str | None = None,
    human_interaction: str = "none",
    policy_ids: list[str] | None = None,
    capability_ids: list[str] | None = None,
    action_method_id: str | None = None,
    task_prompt_id: str | None = None,
    context_profile_id: str | None = None,
    output_contract_id: str | None = None,
    output_mode: str | None = None,
    staging_contract_id: str | None = None,
    merge_action_id: str | None = None,
    allowed_write_paths: list[str] | None = None,
    allowed_read_paths: list[str] | None = None,
    forbidden_write_paths: list[str] | None = None,
    forbidden_read_paths: list[str] | None = None,
    produces: list[str] | None = None,
    consumes: list[str] | None = None,
    schema_version: str = "1",
) -> dict[str, Any]:
    """Declare a Pilot Action with compositional references.

    ``actors`` is derived from ``agent_id`` for authorize / spawn checks.
    Workflow Spec is the sole editable authority for identity fields.
    ``human_interaction`` is ``none`` | ``confirm`` | ``approve``.
    ``produces`` / ``consumes`` are optional Producer/Consumer DAG edges;
    when ``produces`` is omitted (None), artifact_dag auto-fills from contracts.
    """
    from ascendc_pilot.ownership import (
        ACTION_FORBIDDEN_READ_PATHS,
        ACTION_FINALIZER_WRITE_PATHS,
        ACTION_PRODUCER_WRITE_PATHS,
        ACTION_READ_PATHS,
        ACTION_WRITE_PATHS,
        infer_execution_mode,
    )

    hi = str(human_interaction or "none").strip().lower()
    if hi not in {"none", "confirm", "approve"}:
        raise ValueError(f"{workflow_id}/{action_id}: invalid human_interaction={human_interaction!r}")
    method_id = action_method_id or f"{workflow_id}/{action_id.replace('_', '-')}"
    actors = [agent_id] if agent_id else []
    mode = infer_execution_mode(
        agent_id=agent_id,
        role_id=role_id,
        execution_mode=execution_mode,
    )
    writes = allowed_write_paths
    if writes is None:
        if output_mode == "staged" and role_id == "producer":
            writes = list((ACTION_PRODUCER_WRITE_PATHS.get(workflow_id) or {}).get(action_id) or [])
        if not writes:
            writes = list((ACTION_WRITE_PATHS.get(workflow_id) or {}).get(action_id) or [])
    reads = allowed_read_paths
    if reads is None:
        reads = list((ACTION_READ_PATHS.get(workflow_id) or {}).get(action_id) or [])
    forbid_reads = forbidden_read_paths
    if forbid_reads is None:
        forbid_reads = list((ACTION_FORBIDDEN_READ_PATHS.get(workflow_id) or {}).get(action_id) or [])
    # Staged producers must not write finalizer canonical paths.
    forbid_writes = list(forbidden_write_paths or [])
    if output_mode == "staged" and role_id == "producer":
        for p in (ACTION_FINALIZER_WRITE_PATHS.get(workflow_id) or {}).get(action_id) or []:
            if p not in forbid_writes:
                forbid_writes.append(p)
    row: dict[str, Any] = {
        "id": action_id,
        "label_zh": label_zh,
        "phases": list(phases),
        "checker_required": checker_required,
        "referee_required": referee_required,
        "gates": list(gates or []),
        "agent_id": agent_id,
        "role_id": role_id,
        "execution_mode": mode,
        "human_interaction": hi,
        "policy_ids": list(policy_ids if policy_ids is not None else DEFAULT_POLICY_IDS),
        "capability_ids": _merge_capability_ids(capability_ids),
        "action_method_id": method_id,
        "task_prompt_id": task_prompt_id,
        "context_profile_id": context_profile_id or f"{workflow_id}-{action_id.replace('_', '-')}",
        "output_contract_id": output_contract_id,
        "allowed_write_paths": list(writes or []),
        "allowed_read_paths": list(reads or []),
        "forbidden_write_paths": list(forbid_writes),
        "forbidden_read_paths": list(forbid_reads or []),
        # Derived for authorize / Task spawn (single primary actor).
        "actors": actors,
        "schema_version": str(schema_version or "1"),
        # None → artifact_dag.normalize_produces auto-fills from contracts.
        "produces": list(produces) if produces is not None else None,
        "consumes": list(consumes) if consumes is not None else [],
    }
    if output_mode:
        row["output_mode"] = output_mode
    if staging_contract_id:
        row["staging_contract_id"] = staging_contract_id
    if merge_action_id:
        row["merge_action_id"] = merge_action_id
    return row


# Static obligation id → gate id that settles it when that gate passes.
STATIC_OBLIGATION_GATE_MAP: dict[str, str] = {
    "scope_validated": "scope_receipt",
    "uo_product_ready": "uo_product_ready",
    "kb_integrity_passed": "integrity",
    "kb_ready": "kb_ready",
    "uo_ready": "uo_ready",
    "init_confirmed": "init_confirmed",
    "plan_approved": "plan_approved",
    "closure_soundness": "closure_soundness",
    "impact_ledger_ready": "impact_ledger_ready",
    "obligations_classified": "obligations_classified",
    "ce_certificate_sound": "ce_certificate_sound",
}

CLOSED_OBLIGATION_STATUSES = frozenset(
    {
        "resolved",
        "verified",
        "not_applicable",
        "human_required",
        "rejected",
    }
)

_CAPS_CODE = ["source-reading", "source-navigation", "kb-query"]
_CAPS_EXTRACT = [
    "source-reading",
    "source-navigation",
    "kb-query",
    "structured-ir-query",
    "readonly-source-search",
    "action-scratch",
    "sharded-llm-producer",
    "bounded-semantic-batch",
    "producer-self-check",
]
_CAPS_ADJUDICATE = [
    "source-reading",
    "source-navigation",
    "kb-query",
    "structured-ir-query",
    "readonly-source-search",
    "action-scratch",
    "sharded-semantic-producer",
    "sharded-llm-producer",
    "bounded-semantic-batch",
    "producer-self-check",
]
_CAPS_INVESTIGATE = [
    "source-reading",
    "source-navigation",
    "kb-query",
    "action-scratch",
]
_CAPS_REVIEW = ["kb-query"]
_CAPS_CONTRACT = ["contract-building", "kb-query"]
_CAPS_OBLIGATION = ["kb-query"]

WORKFLOWS: dict[str, dict[str, Any]] = {
    "uo-init": {
        "slash": "/uo-init",
        "engine": "uo",
        "cognitive_skill_id": "operator-analysis",
        "requires_project": True,
        "requires_architecture": True,
        "requires_uo_product": False,
        "entry_state": "prepare",
        "terminal_ready_states": ["verify"],
        "retry_budget": 3,
        "states": [
            _st("prepare", "准备 BuildVariant / 范围"),
            _st("extract", "Clang 抽取 CompilerFacts"),
            _st("analyze", "确定性 CodeMap Pass"),
            _st("commit", "写入 operator.uo"),
            _st("verify", "结构合法性校验"),
        ],
        "transitions": [
            _tr("prepare", "extract"),
            _tr("extract", "analyze"),
            _tr("analyze", "commit"),
            _tr("commit", "verify"),
            _tr("extract", "prepare", kind="rework", reason_codes=["SCOPE_REWORK", "SCOPE_FAILED"]),
            _tr("analyze", "extract", kind="rework", reason_codes=["EXTRACT_REWORK"]),
            _tr("commit", "analyze", kind="rework", reason_codes=["INTEGRITY_REWORK", "GAP_REWORK"]),
            _tr("verify", "analyze", kind="rework", reason_codes=["CODEMAP_VERIFY_REWORK"]),
            _tr("verify", "commit", kind="rework", reason_codes=["export_kb", "integrity"]),
            _tr("verify", "prepare", kind="rework", reason_codes=["scope", "SCOPE_REWORK"]),
        ],
        "phase_gates": {
            "prepare": ["layout_receipt", "scope_receipt"],
            "extract": ["extract_receipt"],
            "analyze": [],
            "commit": ["uo_product_ready"],
            "verify": [],
        },
        "pipelines": {
            "prepare": ["prepare"],
            "extract": ["extract"],
            "analyze": ["analyze"],
            "commit": ["commit"],
            "verify": ["verify"],
        },
        "complete_gates": ["scope_receipt", "uo_product_ready"],
        "meta": {
            "product": "codemap-uo",
            "canonical_policy": "compiler_plus_deterministic_only",
            "unresolved_policy": "retain",
            "recovery_by_reason": {
                "SCOPE_REWORK": {
                    "type": "transition",
                    "target_phase": "prepare",
                    "next_action": "prepare",
                },
                "EXTRACT_REWORK": {"type": "action", "action_id": "extract"},
                "GAP_REWORK": {"type": "action", "action_id": "analyze"},
                "INTEGRITY_REWORK": {"type": "action", "action_id": "commit"},
                "CODEMAP_VERIFY_REWORK": {"type": "action", "action_id": "verify"},
            },
        },
        "actions": [
            _act(
                "prepare",
                label_zh="准备范围与 BuildVariant",
                phases=["prepare"],
                workflow_id="uo-init",
                agent_id=None,
                role_id="deterministic_engine",
                execution_mode="deterministic",
                gates=["layout_receipt", "scope_receipt"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="uo-prepare-v1",
            ),
            _act(
                "extract",
                label_zh="Clang 抽取 CompilerFacts",
                phases=["extract"],
                workflow_id="uo-init",
                agent_id=None,
                role_id="deterministic_engine",
                gates=["extract_receipt"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="uo-extract-v1",
            ),
            _act(
                "analyze",
                label_zh="确定性 CodeMap Pass",
                phases=["analyze"],
                workflow_id="uo-init",
                agent_id=None,
                role_id="deterministic_engine",
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="uo-analyze-v1",
            ),
            _act(
                "commit",
                label_zh="写入 operator.uo CodeMap",
                phases=["commit"],
                workflow_id="uo-init",
                agent_id=None,
                role_id="deterministic_engine",
                gates=["uo_product_ready"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="uo-commit-v1",
            ),
            _act(
                "verify",
                label_zh="CodeMap 结构合法性校验",
                phases=["verify"],
                workflow_id="uo-init",
                agent_id=None,
                role_id="deterministic_engine",
                referee_required=False,
                gates=[],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="uo-verify-v1",
            ),
        ],
        "agents": [{"id": "ascendc-pilot", "role": "controller"}],
        "static_obligations": [
            {"id": "scope_validated", "label_zh": "范围已校验"},
            {"id": "uo_product_ready", "label_zh": ".uo CodeMap 已写入"},
        ],
        "dynamic_obligation_sources": ["ir/unresolved.yaml"],
        "write_roots": ["uo", "runs", "state", "context"],
        "reset_policy": {
            "reinit_delete": ["uo"],
            "reinit_preserve": [],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["prepare", "extract", "analyze", "commit", "verify"],
        "gates": [
            "layout_receipt",
            "scope_receipt",
            "extract_receipt",
            "uo_product_ready",
        ],
    },
    "uo-update": {
        "slash": "/uo-update",
        "engine": "uo",
        "cognitive_skill_id": "operator-analysis",
        "requires_project": True,
        "requires_architecture": True,
        "requires_uo_product": False,
        "entry_state": "detect",
        "terminal_ready_states": ["diff"],
        "retry_budget": 3,
        "states": [
            _st("detect", "变更检测"),
            _st("plan", "更新计划"),
            _st("apply", "应用变更"),
            _st("export", "导出与校验"),
            _st("diff", "差异摘要"),
        ],
        "transitions": [
            _tr("detect", "plan"),
            _tr("plan", "apply"),
            _tr("apply", "export"),
            _tr("export", "diff"),
            _tr(
                "export",
                "apply",
                kind="rework",
                reason_codes=["EXTRACT_REWORK", "INTEGRITY_REWORK"],
            ),
            _tr("detect", "diff", kind="forward", reason_codes=["DIFF_ONLY"]),
        ],
        "phase_gates": {
            "export": ["integrity"],
        },
        "pipelines": {
            "detect": ["detect_changes"],
            "plan": ["plan_update"],
            "apply": ["apply_update"],
            "export": ["export_integrity"],
            "diff": ["diff_summary"],
        },
        "complete_gates": [
            "integrity",
        ],
        "complete_gates_diff_only": [],
        "actions": [
            _act(
                "detect_changes",
                label_zh="检测源码变更",
                phases=["detect"],
                workflow_id="uo-update",
                agent_id=None,
                role_id="deterministic_engine",
                execution_mode="deterministic",
                capability_ids=[],
                output_contract_id="change-detect-v1",
            ),
            _act(
                "plan_update",
                label_zh="规划 CodeMap 增量更新",
                phases=["plan"],
                workflow_id="uo-update",
                agent_id=None,
                role_id="deterministic_engine",
                execution_mode="deterministic",
                capability_ids=[],
                output_contract_id="update-plan-v1",
            ),
            _act(
                "apply_update",
                label_zh="应用 CodeMap 增量更新",
                phases=["apply"],
                workflow_id="uo-update",
                agent_id=None,
                role_id="deterministic_engine",
                execution_mode="deterministic",
                capability_ids=[],
                output_contract_id="update-apply-v1",
            ),
            _act(
                "export_integrity",
                label_zh="校验 CodeMap 完整性",
                phases=["export"],
                workflow_id="uo-update",
                agent_id=None,
                role_id="deterministic_engine",
                execution_mode="deterministic",
                gates=["integrity"],
                capability_ids=[],
                output_contract_id="integrity-v1",
            ),
            _act(
                "diff_summary",
                label_zh="CodeMap 差异摘要",
                phases=["diff", "detect"],
                workflow_id="uo-update",
                checker_required=False,
                agent_id=None,
                role_id="deterministic_engine",
                execution_mode="deterministic",
                capability_ids=[],
                output_contract_id="diff-summary-v1",
            ),
            _act(
                "diff_only",
                label_zh="仅生成 CodeMap 差异摘要",
                phases=["detect", "diff"],
                workflow_id="uo-update",
                checker_required=False,
                agent_id=None,
                role_id="deterministic_engine",
                execution_mode="deterministic",
                capability_ids=[],
                output_contract_id="diff-summary-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-uo-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [{"id": "kb_integrity_passed", "label_zh": "完整性通过"}],
        "dynamic_obligation_sources": ["ir/unresolved.yaml"],
        "write_roots": ["uo", "runs", "state", "context"],
        "reset_policy": {
            "reinit_delete": [
                "uo/diff",
                "uo/summary/update_plan.yaml",
            ],
            "reinit_preserve": ["uo"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["detect", "plan", "apply", "export", "diff"],
        "gates": [
            "integrity",
        ],
    },
    "uo-query": {
        "slash": "/uo-query",
        "engine": "uo",
        "cognitive_skill_id": "operator-analysis",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "entry_state": "route",
        "terminal_ready_states": ["answer"],
        "retry_budget": 3,
        "states": [
            _st("route", "问题路由"),
            _st("lookup", "知识检索"),
            _st("answer", "回答"),
        ],
        "transitions": [
            _tr("route", "lookup"),
            _tr("lookup", "answer"),
            _tr("lookup", "lookup", kind="rework", reason_codes=["LOOKUP_REWORK"]),
        ],
        "phase_gates": {},
        "complete_gates": [],
        "actions": [
            _act(
                "kb_lookup",
                label_zh="CodeMap 查询",
                phases=["route", "lookup", "answer"],
                workflow_id="uo-query",
                agent_id="uo-query",
                role_id="readonly_analyst",
                gates=[],
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                task_prompt_id="uo/codemap-query",
                output_contract_id="kb-answer-v1",
                # Ephemeral Q&A: subagent returns kb-answer-v1; finalize materializes.
                output_mode="return_value",
                allowed_write_paths=[
                    "runs/{run_id}/actions/kb_lookup/answer.yaml",
                    "runs/{run_id}/actions/kb_lookup/scratch/**",
                ],
            ),
        ],
        "agents": [{"id": "uo-query", "role": "readonly_analyst"}],
        "static_obligations": [],
        "dynamic_obligation_sources": [],
        "write_roots": ["runs", "context", "memory"],
        "reset_policy": {
            "reinit_delete": [],
            "reinit_preserve": ["uo", "tg", "ce"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["route", "lookup", "answer"],
        "gates": [],
    },
    "uo-investigate": {
        "slash": "/uo-investigate",
        "engine": "uo",
        "cognitive_skill_id": "operator-analysis",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "entry_state": "investigate",
        "terminal_ready_states": ["report"],
        "retry_budget": 2,
        "states": [
            _st("investigate", "调查 unresolved residual"),
            _st("report", "输出调查报告"),
        ],
        "transitions": [
            _tr("investigate", "report"),
        ],
        "phase_gates": {},
        "pipelines": {
            "investigate": ["investigate"],
            "report": [],
        },
        "complete_gates": [],
        "meta": {
            "product": "gap-investigation",
            "canonical_policy": "read_only_no_uo_mutation",
            "purpose": "Classify deterministic-engine gaps; never patch canonical .uo",
        },
        "actions": [
            _act(
                "investigate",
                label_zh="调查 semantic residual",
                phases=["investigate", "report"],
                workflow_id="uo-investigate",
                agent_id="uo-gap-investigator",
                role_id="readonly_analyst",
                execution_mode="subagent",
                gates=[],
                capability_ids=_CAPS_INVESTIGATE,
                task_prompt_id="uo/investigate-gaps",
                output_contract_id="uo-investigate-v1",
                allowed_write_paths=[
                    "runs/{run_id}/actions/investigate/parts/**",
                    "runs/{run_id}/actions/investigate/scratch/**",
                    "runs/{run_id}/actions/investigate/report.yaml",
                    "uo/ir/gap_investigation.yaml",
                ],
            ),
        ],
        "agents": [
            {"id": "uo-gap-investigator", "role": "readonly_analyst"},
            {"id": "ascendc-pilot", "role": "controller"},
        ],
        "static_obligations": [],
        "dynamic_obligation_sources": ["ir/unresolved.yaml"],
        "write_roots": ["runs", "context", "uo/ir"],
        "reset_policy": {
            "reinit_delete": [],
            "reinit_preserve": ["uo", "tg", "ce"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["investigate", "report"],
        "gates": [],
    },
    "ce-review": {
        "slash": "/ce-review",
        "engine": "ce",
        "cognitive_skill_id": "code-review",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "entry_state": "context",
        "terminal_ready_states": ["summary"],
        "retry_budget": 3,
        "states": [
            _st("context", "组装上下文"),
            _st("bug", "缺陷审查"),
            _st("functional", "功能审查"),
            _st("summary", "汇总"),
        ],
        "transitions": [
            _tr("context", "bug"),
            _tr("bug", "functional"),
            _tr("functional", "summary"),
        ],
        "phase_gates": {"context": ["kb_ready", "context_pack"]},
        "complete_gates": ["kb_ready", "context_pack"],
        "pipelines": {
            "context": ["code_review"],
            "bug": ["code_review"],
            "functional": ["code_review"],
            "summary": ["code_review"],
        },
        "actions": [
            _act(
                "code_review",
                label_zh="代码审查",
                phases=["context", "bug", "functional", "summary"],
                workflow_id="ce-review",
                agent_id="ce-reviewer",
                role_id="readonly_reviewer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                task_prompt_id="ce/code-review",
                output_contract_id="code-review-v1",
                gates=["kb_ready", "context_pack"],
            ),
        ],
        "agents": [{"id": "ce-reviewer", "role": "readonly_reviewer"}],
        "static_obligations": [{"id": "kb_ready", "label_zh": "KB 就绪"}],
        "dynamic_obligation_sources": [],
        "write_roots": ["ce/review", "ce/verify", "runs", "context"],
        "reset_policy": {
            "reinit_delete": ["ce/review"],
            "reinit_preserve": ["uo", "tg"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["context", "bug", "functional", "summary"],
        "gates": ["kb_ready", "context_pack"],
    },
    "ce-impact": {
        "slash": "/ce-impact",
        "engine": "ce",
        "cognitive_skill_id": "code-review",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "entry_state": "capture",
        "terminal_ready_states": ["audit"],
        "retry_budget": 3,
        "states": [
            _st("capture", "捕获变更"),
            _st("freshness", "校验 CodeMap 新鲜度"),
            _st("slice", "计算影响切片"),
            _st("classify", "风险分类"),
            _st("obligations", "建立验证义务"),
            _st("audit", "审计影响账本"),
        ],
        "transitions": [
            _tr("capture", "freshness"),
            _tr("freshness", "slice"),
            _tr("slice", "classify"),
            _tr("classify", "obligations"),
            _tr("obligations", "audit"),
            _tr("audit", "obligations", kind="rework", reason_codes=["OBLIGATION_REWORK"]),
        ],
        "phase_gates": {
            "freshness": ["kb_ready"],
            "obligations": ["obligations_classified"],
            "audit": ["impact_ledger_ready"],
        },
        "complete_gates": ["kb_ready", "obligations_classified", "impact_ledger_ready"],
        "pipelines": {
            "capture": ["change_capture"],
            "freshness": ["uo_freshness"],
            "slice": ["impact_slice"],
            "classify": ["risk_classify"],
            "obligations": ["obligation_build"],
            "audit": ["impact_audit"],
        },
        "meta": {
            "recovery_by_reason": {
                "OBLIGATION_REWORK": {"type": "phase", "phase": "obligations"},
            },
        },
        "actions": [
            _act(
                "change_capture",
                label_zh="捕获可复现变更",
                phases=["capture"],
                workflow_id="ce-impact",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="change-capture-v1",
            ),
            _act(
                "uo_freshness",
                label_zh="校验 CodeMap 指纹",
                phases=["freshness"],
                workflow_id="ce-impact",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                gates=["kb_ready"],
                capability_ids=["kb-query"],
                output_contract_id="uo-freshness-v1",
            ),
            _act(
                "impact_slice",
                label_zh="生成变更影响切片",
                phases=["slice"],
                workflow_id="ce-impact",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=["kb-query"],
                output_contract_id="impact-slice-v1",
            ),
            _act(
                "risk_classify",
                label_zh="分类影响风险",
                phases=["classify"],
                workflow_id="ce-impact",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="risk-classify-v1",
            ),
            _act(
                "obligation_build",
                label_zh="建立验证义务账本",
                phases=["obligations"],
                workflow_id="ce-impact",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                gates=["obligations_classified"],
                capability_ids=[],
                output_contract_id="obligation-ledger-v1",
            ),
            _act(
                "impact_audit",
                label_zh="审计影响与验证义务",
                phases=["audit"],
                workflow_id="ce-impact",
                agent_id="ce-change-referee",
                role_id="referee",
                referee_required=True,
                gates=["impact_ledger_ready"],
                capability_ids=["kb-query", "source-reading"],
                task_prompt_id="ce/impact-audit",
                output_contract_id="impact-audit-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-ce-engine", "role": "deterministic_engine"},
            {"id": "ce-change-referee", "role": "referee"},
        ],
        "static_obligations": [
            {"id": "impact_ledger_ready", "label_zh": "影响账本已建立"},
            {"id": "obligations_classified", "label_zh": "验证义务已分类"},
        ],
        "dynamic_obligation_sources": ["ce/impact/ledger.yaml"],
        "write_roots": ["ce/impact", "runs", "context"],
        "reset_policy": {
            "reinit_delete": ["ce/impact"],
            "reinit_preserve": ["uo", "tg"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["capture", "freshness", "slice", "classify", "obligations", "audit"],
        "gates": ["kb_ready", "obligations_classified", "impact_ledger_ready"],
    },
    "ce-verify": {
        "slash": "/ce-verify",
        "engine": "ce",
        "cognitive_skill_id": "code-review",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "entry_state": "gate",
        "terminal_ready_states": ["certify"],
        "retry_budget": 3,
        "states": [
            _st("gate", "验证前置"),
            _st("review", "义务驱动审查"),
            _st("coverage", "桥接 TG 覆盖证据"),
            _st("residual", "分析剩余义务"),
            _st("external", "摄取外部证据"),
            _st("certify", "签发 CE 证书"),
        ],
        "transitions": [
            _tr("gate", "review"),
            _tr("review", "coverage"),
            _tr("coverage", "residual"),
            _tr("residual", "external"),
            _tr("external", "certify"),
            _tr("certify", "residual", kind="rework", reason_codes=["OBLIGATION_REWORK"]),
        ],
        "phase_gates": {
            "gate": ["impact_ledger_ready"],
            "certify": ["ce_certificate_sound"],
        },
        "complete_gates": ["impact_ledger_ready", "ce_certificate_sound"],
        "pipelines": {
            "gate": ["verify_gate"],
            "review": ["code_review"],
            "coverage": ["coverage_bridge"],
            "residual": ["residual_analyse"],
            "external": ["external_ingest", "exclusion_review"],
            "certify": ["ce_certify"],
        },
        "meta": {
            "recovery_by_reason": {
                "OBLIGATION_REWORK": {"type": "phase", "phase": "residual"},
            },
        },
        "actions": [
            _act(
                "verify_gate",
                label_zh="校验影响账本",
                phases=["gate"],
                workflow_id="ce-verify",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                gates=["impact_ledger_ready"],
                capability_ids=[],
                output_contract_id="verify-gate-v1",
            ),
            _act(
                "code_review",
                label_zh="按义务执行代码审查",
                phases=["review"],
                workflow_id="ce-verify",
                agent_id="ce-reviewer",
                role_id="readonly_reviewer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                task_prompt_id="ce/code-review",
                output_contract_id="verify-code-review-v1",
            ),
            _act(
                "coverage_bridge",
                label_zh="桥接 TG 覆盖证据",
                phases=["coverage"],
                workflow_id="ce-verify",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="coverage-bridge-v1",
            ),
            _act(
                "residual_analyse",
                label_zh="分析未闭合验证义务",
                phases=["residual"],
                workflow_id="ce-verify",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="residual-analysis-v1",
            ),
            _act(
                "external_ingest",
                label_zh="摄取声明的外部证据",
                phases=["external"],
                workflow_id="ce-verify",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="external-evidence-v1",
            ),
            _act(
                "exclusion_review",
                label_zh="审查义务排除项",
                phases=["external"],
                workflow_id="ce-verify",
                agent_id="ce-change-referee",
                role_id="referee",
                referee_required=True,
                capability_ids=["kb-query", "source-reading"],
                task_prompt_id="ce/exclusion-review",
                output_contract_id="exclusion-review-v1",
            ),
            _act(
                "ce_certify",
                label_zh="签发 CE 验证证书",
                phases=["certify"],
                workflow_id="ce-verify",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                gates=["ce_certificate_sound"],
                capability_ids=[],
                output_contract_id="ce-certificate-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-ce-engine", "role": "deterministic_engine"},
            {"id": "ce-reviewer", "role": "readonly_reviewer"},
            {"id": "ce-change-referee", "role": "referee"},
        ],
        "static_obligations": [
            {"id": "ce_certificate_sound", "label_zh": "CE 验证证书健全"},
        ],
        "dynamic_obligation_sources": ["ce/impact/ledger.yaml", "ce/verify/residual.yaml"],
        "write_roots": ["ce/verify", "runs", "context"],
        "reset_policy": {
            "reinit_delete": ["ce/verify"],
            "reinit_preserve": ["uo", "tg", "ce/impact"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["gate", "review", "coverage", "residual", "external", "certify"],
        "gates": ["impact_ledger_ready", "ce_certificate_sound"],
    },
    "ce-intent": {
        "slash": "/ce-intent",
        "engine": "ce",
        "cognitive_skill_id": "code-review",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "entry_state": "intent",
        "terminal_ready_states": ["confirm"],
        "retry_budget": 3,
        "states": [
            _st("intent", "捕获变更意图"),
            _st("kb_ready", "校验知识库"),
            _st("decompose", "分解特性"),
            _st("locate", "定位代码锚点"),
            _st("review", "审查变更计划"),
            _st("confirm", "人工确认"),
        ],
        "transitions": [
            _tr("intent", "kb_ready"),
            _tr("kb_ready", "decompose"),
            _tr("decompose", "locate"),
            _tr("locate", "review"),
            _tr("review", "confirm"),
        ],
        "phase_gates": {"kb_ready": ["kb_ready"]},
        "complete_gates": ["kb_ready"],
        "pipelines": {
            "intent": ["intent_capture"],
            "kb_ready": ["kb_check"],
            "decompose": ["feature_decompose"],
            "locate": ["anchor_locate"],
            "review": ["plan_review"],
            "confirm": ["human_confirm"],
        },
        "actions": [
            _act(
                "intent_capture",
                label_zh="捕获变更意图",
                phases=["intent"],
                workflow_id="ce-intent",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="intent-capture-v1",
            ),
            _act(
                "kb_check",
                label_zh="校验 CodeMap 就绪",
                phases=["kb_ready"],
                workflow_id="ce-intent",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                gates=["kb_ready"],
                capability_ids=["kb-query"],
                output_contract_id="intent-kb-check-v1",
            ),
            _act(
                "feature_decompose",
                label_zh="分解变更特性",
                phases=["decompose"],
                workflow_id="ce-intent",
                agent_id="ce-analyst",
                role_id="producer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                task_prompt_id="ce/feature-decompose",
                output_contract_id="feature-decompose-v1",
                output_mode="staged",
                staging_contract_id="feature-decompose-staging-v1",
                merge_action_id="plan_review",
            ),
            _act(
                "anchor_locate",
                label_zh="定位 CodeMap 锚点",
                phases=["locate"],
                workflow_id="ce-intent",
                agent_id="deterministic-ce-engine",
                role_id="deterministic_engine",
                capability_ids=["kb-query"],
                output_contract_id="anchor-locate-v1",
            ),
            _act(
                "plan_review",
                label_zh="审查变更计划",
                phases=["review"],
                workflow_id="ce-intent",
                agent_id="ce-change-referee",
                role_id="referee",
                referee_required=True,
                capability_ids=["kb-query", "source-reading"],
                task_prompt_id="ce/plan-review",
                output_contract_id="plan-review-v1",
            ),
            _act(
                "human_confirm",
                label_zh="确认变更计划",
                phases=["confirm"],
                workflow_id="ce-intent",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                human_interaction="confirm",
                capability_ids=[],
                task_prompt_id="ce/human-confirm",
                output_contract_id="intent-confirmed-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-ce-engine", "role": "deterministic_engine"},
            {"id": "ce-analyst", "role": "producer"},
            {"id": "ce-change-referee", "role": "referee"},
            {"id": "ascendc-pilot", "role": "controller"},
        ],
        "static_obligations": [],
        "dynamic_obligation_sources": ["ce/intent/feature_decomposition.yaml"],
        "write_roots": ["ce/intent", "runs", "context"],
        "reset_policy": {
            "reinit_delete": ["ce/intent"],
            "reinit_preserve": ["uo", "tg", "ce/impact", "ce/verify"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["intent", "kb_ready", "decompose", "locate", "review", "confirm"],
        "gates": ["kb_ready"],
    },
    "tg-init": {
        "slash": "/tg-init",
        "engine": "tg",
        "cognitive_skill_id": "testcase-generation",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "entry_state": "intent",
        "terminal_ready_states": ["confirm"],
        "retry_budget": 3,
        # Base = tilingkey_full_coverage.
        "states": [
            _st("intent", "记录全覆盖模式"),
            _st("kb_ready", "校验知识库"),
            _st("contract", "建立覆盖合同"),
            _st("bind", "建立 Host 视图绑定"),
            _st("gate", "完整性与审计"),
            _st("confirm", "确认进入规划"),
        ],
        "transitions": [
            _tr("intent", "kb_ready"),
            _tr("kb_ready", "contract"),
            _tr("contract", "bind"),
            _tr("bind", "gate"),
            _tr("gate", "confirm"),
            _tr("gate", "bind", kind="rework", reason_codes=["BIND_REWORK"]),
            _tr("confirm", "gate", kind="rework", reason_codes=["AUDIT_REWORK"]),
        ],
        "phase_gates": {
            "kb_ready": ["uo_ready"],
            "bind": ["tilingkey_binding_ready"],
            "gate": ["audit_pass"],
            "confirm": ["init_confirmed", "kb_fingerprint_fresh"],
        },
        "complete_gates": [
            "uo_ready",
            "tilingkey_binding_ready",
            "audit_pass",
            "init_confirmed",
            "kb_fingerprint_fresh",
        ],
        "pipelines": {
            "intent": ["init_intent"],
            "kb_ready": ["kb_check"],
            "contract": ["contract_build"],
            "bind": ["semantic_bind"],
            "gate": ["integrity_gate", "init_audit"],
            "confirm": ["human_confirm"],
        },
        "actions": [
            _act(
                "init_intent",
                label_zh="采用默认全覆盖模式",
                phases=["intent"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-init-intent-v1",
            ),
            _act(
                "kb_check",
                label_zh="校验定稿知识库",
                phases=["kb_ready"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["uo_ready"],
                capability_ids=["kb-query"],
                output_contract_id="uo-ready-v1",
            ),
            _act(
                "contract_build",
                label_zh="建立覆盖合同骨架",
                phases=["contract"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=_CAPS_CONTRACT,
                output_contract_id="tilingkey-contract-v1",
            ),
            _act(
                "semantic_bind",
                label_zh="建立 Host 视图绑定",
                phases=["bind"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["tilingkey_binding_ready"],
                capability_ids=["kb-query"],
                output_contract_id="tilingkey-binding-v1",
            ),
            _act(
                "integrity_gate",
                label_zh="完整性校验",
                phases=["gate"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=[],
                capability_ids=[],
                output_contract_id="tilingkey-integrity-v1",
            ),
            _act(
                "init_audit",
                label_zh="审计覆盖合同",
                phases=["gate"],
                workflow_id="tg-init",
                agent_id="tg-init-audit",
                role_id="referee",
                referee_required=True,
                gates=["audit_pass"],
                capability_ids=_CAPS_REVIEW,
                task_prompt_id="tg/init-audit",
                output_contract_id="init-audit-v1",
            ),
            _act(
                "human_confirm",
                label_zh="确认进入规划",
                phases=["confirm"],
                workflow_id="tg-init",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                human_interaction="confirm",
                gates=["init_confirmed", "kb_fingerprint_fresh"],
                capability_ids=[],
                task_prompt_id="tg/human-confirm",
                output_contract_id="init-confirmed-v1",
            ),
        ],
        "agents": [
            {"id": "tg-init-audit", "role": "referee"},
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
            {"id": "ascendc-pilot", "role": "controller"},
        ],
        "static_obligations": [
            {"id": "uo_ready", "label_zh": "知识库就绪"},
            {"id": "init_confirmed", "label_zh": "已确认进入规划"},
        ],
        "dynamic_obligation_sources": [
            "realization/unresolved.yaml",
            "realization/binding_gaps.yaml",
        ],
        "write_roots": ["tg", "runs", "state", "context"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": ["tg"],
            "reinit_preserve": ["uo"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["intent", "kb_ready", "contract", "bind", "gate", "confirm"],
        "gates": [
            "uo_ready",
            "kb_fingerprint_fresh",
            "tilingkey_binding_ready",
            "audit_pass",
            "init_confirmed",
        ],
        "meta": {"default_mode": "tilingkey_full_coverage"},
        "mode_overlays": {
            "tilingkey_full_coverage": {
                "phases": ["intent", "kb_ready", "contract", "bind", "gate", "confirm"],
                "states": [
                    _st("intent", "记录全覆盖模式"),
                    _st("kb_ready", "校验知识库"),
                    _st("contract", "建立覆盖合同"),
                    _st("bind", "建立 Host 视图绑定"),
                    _st("gate", "完整性与审计"),
                    _st("confirm", "确认进入规划"),
                ],
                "transitions": [
                    _tr("intent", "kb_ready"),
                    _tr("kb_ready", "contract"),
                    _tr("contract", "bind"),
                    _tr("bind", "gate"),
                    _tr("gate", "confirm"),
                    _tr("gate", "bind", kind="rework", reason_codes=["BIND_REWORK"]),
                    _tr("confirm", "gate", kind="rework", reason_codes=["AUDIT_REWORK"]),
                ],
                "phase_gates": {
                    "kb_ready": ["uo_ready"],
                    "bind": ["tilingkey_binding_ready"],
                    "gate": ["audit_pass"],
                    "confirm": ["init_confirmed", "kb_fingerprint_fresh"],
                },
                "complete_gates": [
                    "uo_ready",
                    "tilingkey_binding_ready",
                    "audit_pass",
                    "init_confirmed",
                    "kb_fingerprint_fresh",
                ],
                "pipelines": {
                    "intent": ["init_intent"],
                    "kb_ready": ["kb_check"],
                    "contract": ["contract_build"],
                    "bind": ["semantic_bind"],
                    "gate": ["integrity_gate", "init_audit"],
                    "confirm": ["human_confirm"],
                },
                "gates": [
                    "uo_ready",
                    "kb_fingerprint_fresh",
                    "tilingkey_binding_ready",
                    "audit_pass",
                    "init_confirmed",
                ],
                "action_overrides": {
                    "contract_build": {"output_contract_id": "tilingkey-contract-v1"},
                    "semantic_bind": {
                        "output_contract_id": "tilingkey-binding-v1",
                        "agent_id": "deterministic-tg-engine",
                        "role_id": "deterministic_engine",
                        "gates": ["tilingkey_binding_ready"],
                        "task_prompt_id": None,
                        "output_mode": None,
                        "staging_contract_id": None,
                        "merge_action_id": None,
                        "allowed_write_paths": [
                            "tg/realization/binding_inventory.yaml",
                        ],
                    },
                    "integrity_gate": {
                        "output_contract_id": "tilingkey-integrity-v1",
                        "gates": [],
                    },
                    "human_confirm": {
                        "allowed_write_paths": [
                            "tg/init/status.yaml",
                            "tg/init/kb_fingerprint.yaml",
                            "tg/init/confirmation.yaml",
                        ],
                    },
                },
            }
        },
    },
    "tg-plan": {
        "slash": "/tg-plan",
        "engine": "tg",
        "cognitive_skill_id": "testcase-generation",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "entry_state": "intent",
        "terminal_ready_states": ["approve"],
        "retry_budget": 3,
        "states": [
            _st("intent", "记录规划目标"),
            _st("scope", "确定规划范围"),
            _st("gate", "规划前置检查"),
            _st("build", "生成测试义务"),
            _st("filter", "裁剪义务范围"),
            _st("review", "审查规划结果"),
            _st("approve", "批准开始求解"),
        ],
        "transitions": [
            _tr("intent", "scope"),
            _tr("scope", "gate"),
            _tr("gate", "build"),
            _tr("build", "filter"),
            _tr("filter", "review"),
            _tr("review", "approve"),
            _tr("approve", "review", kind="rework", reason_codes=["PLAN_REWORK"]),
        ],
        "phase_gates": {
            "gate": ["tg_init_confirmed", "kb_fingerprint_fresh"],
            "approve": ["plan_approved"],
        },
        "complete_gates": ["tg_init_confirmed", "plan_approved"],
        "pipelines": {
            "intent": ["plan_intent"],
            "scope": ["plan_scope"],
            "gate": ["plan_precheck"],
            "build": ["plan_build"],
            "filter": ["plan_build"],
            "review": ["plan_build"],
            "approve": ["plan_approve"],
        },
        "actions": [
            _act(
                "plan_intent",
                label_zh="记录规划目标（默认覆盖全部合法 Key）",
                phases=["intent"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                execution_mode="deterministic",
                capability_ids=[],
                task_prompt_id="tg/plan-intent",
                output_contract_id="plan-intent-v1",
            ),
            _act(
                "plan_scope",
                label_zh="确定规划范围",
                phases=["scope"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=_CAPS_OBLIGATION,
                output_contract_id="plan-scope-v1",
            ),
            _act(
                "plan_precheck",
                label_zh="规划前置检查",
                phases=["gate"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["tg_init_confirmed", "kb_fingerprint_fresh"],
                capability_ids=[],
                output_contract_id="plan-precheck-v1",
            ),
            _act(
                "plan_build",
                label_zh="生成测试义务",
                phases=["build", "filter", "review"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=_CAPS_OBLIGATION,
                output_contract_id="plan-build-v1",
            ),
            _act(
                "plan_approve",
                label_zh="批准开始求解",
                phases=["approve"],
                workflow_id="tg-plan",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                human_interaction="approve",
                gates=["plan_approved"],
                capability_ids=[],
                task_prompt_id="tg/plan-approve",
                output_contract_id="plan-approved-v1",
            ),
        ],
        "agents": [
            {"id": "ascendc-pilot", "role": "controller"},
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [{"id": "plan_approved", "label_zh": "已批准开始求解"}],
        "dynamic_obligation_sources": ["plan/**/uncovered_obligations.yaml"],
        "write_roots": ["tg", "runs", "state", "context"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": ["tg/plan", "tg/solve", "tg/cases", "tg/extract"],
            "reinit_preserve": [
                "uo",
                "tg/intake",
                "tg/snapshot",
                "tg/contract",
                "tg/realization",
                "tg/init",
                "tg/run.yaml",
            ],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["intent", "scope", "gate", "build", "filter", "review", "approve"],
        "gates": ["tg_init_confirmed", "plan_approved"],
        "mode_overlays": {
            "ce_change_scoped": {
                # Reuse the proven TG plan machine while declaring that the
                # requested scope originates in CE's audited impact ledger.
                "pipelines": {
                    "intent": ["plan_intent"],
                    "scope": ["plan_scope"],
                    "gate": ["plan_precheck"],
                    "build": ["plan_build"],
                    "filter": ["plan_build"],
                    "review": ["plan_build"],
                    "approve": ["plan_approve"],
                },
                "action_overrides": {
                    "plan_intent": {
                        "label_zh": "记录 CE 变更范围规划目标",
                    },
                    "plan_scope": {
                        "label_zh": "从 CE 影响账本确定规划范围",
                        "allowed_read_paths": [
                            "ce/impact/ledger.yaml",
                            "ce/impact/impact_slice.yaml",
                            "uo/*.uo",
                        ],
                    },
                },
            },
        },
    },
    "tg-solve": {
        "slash": "/tg-solve",
        "engine": "tg",
        "cognitive_skill_id": "testcase-generation",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "entry_state": "gate",
        "terminal_ready_states": ["certify"],
        "retry_budget": 8,
        "states": [
            _st("gate", "求解前置"),
            _st("oracle", "Oracle 探测"),
            _st("ledger", "重建账本"),
            _st("search", "构造并 Replay 一轮"),
            _st("residual", "轮次分析与路由"),
            _st("construct", "定向再构造"),
            _st("lemma", "轮内引理"),
            _st("audit", "闭环审查"),
            _st("certify", "签发证书"),
        ],
        "transitions": [
            _tr("gate", "oracle"),
            _tr("oracle", "ledger"),
            _tr("ledger", "search"),
            _tr("search", "residual"),
            _tr("residual", "audit"),
            _tr("audit", "certify"),
            _tr("construct", "residual"),
            _tr("lemma", "ledger"),
            # residual 回边：每轮分析后立刻分支（不攒到最后再证明）
            _tr("residual", "search", kind="rework", reason_codes=["SEARCH_PROGRESS"]),
            _tr(
                "residual",
                "construct",
                kind="rework",
                reason_codes=["CONSTRUCT_TARGETS", "SEARCH_STALLED"],
            ),
            _tr("residual", "lemma", kind="rework", reason_codes=["NEED_LEMMA"]),
            _tr("audit", "lemma", kind="rework", reason_codes=["AUDIT_REWORK", "LEMMA_REWORK"]),
        ],
        "phase_gates": {
            "gate": ["plan_approved", "kb_fingerprint_fresh"],
            "certify": ["closure_soundness"],
        },
        "complete_gates": ["plan_approved", "closure_soundness"],
        "pipelines": {
            "gate": ["solve_precheck"],
            "oracle": ["oracle_probe"],
            "ledger": ["closure_ledger"],
            "search": ["closure_search"],
            "residual": ["closure_residual"],
            "construct": ["closure_construct", "closure_explain"],
            "lemma": [
                "lemma_leads",
                "lemma_evidence",
                "lemma_mine",
                "lemma_verify",
                "lemma_review",
                "lemma_apply",
                "lemma_loop",
            ],
            "audit": ["closure_audit"],
            "certify": ["closure_certify"],
        },
        "mode_overlays": {
            "tilingkey_full_coverage": {
                "terminal_ready_states": ["certify"],
                "complete_gates": ["plan_approved", "closure_soundness"],
                "transitions": [
                    _tr("gate", "oracle"),
                    _tr("oracle", "ledger"),
                    _tr("ledger", "search"),
                    _tr("search", "residual"),
                    _tr("residual", "audit"),
                    _tr("audit", "certify"),
                    _tr("construct", "residual"),
                    _tr("lemma", "ledger"),
                    _tr("residual", "search", kind="rework", reason_codes=["SEARCH_PROGRESS"]),
                    _tr(
                        "residual",
                        "construct",
                        kind="rework",
                        reason_codes=["CONSTRUCT_TARGETS", "SEARCH_STALLED"],
                    ),
                    _tr("residual", "lemma", kind="rework", reason_codes=["NEED_LEMMA"]),
                    _tr("audit", "lemma", kind="rework", reason_codes=["AUDIT_REWORK", "LEMMA_REWORK"]),
                ],
                "pipelines": {
                    "gate": ["solve_precheck"],
                    "oracle": ["oracle_probe"],
                    "ledger": ["closure_ledger"],
                    "search": ["closure_search"],
                    "residual": ["closure_residual"],
                    "construct": ["closure_construct", "closure_explain"],
                    "lemma": [
                        "lemma_leads",
                        "lemma_evidence",
                        "lemma_mine",
                        "lemma_verify",
                        "lemma_review",
                        "lemma_apply",
                        "lemma_loop",
                    ],
                    "audit": ["closure_audit"],
                    "certify": ["closure_certify"],
                },
            },
            # Same phase machine as tilingkey_full_coverage; plan level L3 selects
            # (key, site, outcome) obligations. No separate td-* workflow.
            "branch_outcome_coverage": {
                "terminal_ready_states": ["certify"],
                "complete_gates": ["plan_approved", "closure_soundness"],
                "plan_level": "L3",
                "transitions": [
                    _tr("gate", "oracle"),
                    _tr("oracle", "ledger"),
                    _tr("ledger", "search"),
                    _tr("search", "residual"),
                    _tr("residual", "audit"),
                    _tr("audit", "certify"),
                    _tr("construct", "residual"),
                    _tr("lemma", "ledger"),
                    _tr("residual", "search", kind="rework", reason_codes=["SEARCH_PROGRESS"]),
                    _tr(
                        "residual",
                        "construct",
                        kind="rework",
                        reason_codes=["CONSTRUCT_TARGETS", "SEARCH_STALLED"],
                    ),
                    _tr("residual", "lemma", kind="rework", reason_codes=["NEED_LEMMA"]),
                    _tr("audit", "lemma", kind="rework", reason_codes=["AUDIT_REWORK", "LEMMA_REWORK"]),
                ],
                "pipelines": {
                    "gate": ["solve_precheck"],
                    "oracle": ["oracle_probe"],
                    "ledger": ["closure_ledger"],
                    "search": ["closure_search"],
                    "residual": ["closure_residual"],
                    "construct": ["closure_construct", "closure_explain"],
                    "lemma": [
                        "lemma_leads",
                        "lemma_evidence",
                        "lemma_mine",
                        "lemma_verify",
                        "lemma_review",
                        "lemma_apply",
                        "lemma_loop",
                    ],
                    "audit": ["closure_audit"],
                    "certify": ["closure_certify"],
                },
            }
        },
        "meta": {
            "default_mode": "tilingkey_full_coverage",
            "capability_ids": [],
            "recovery_by_reason": {
                "SEARCH_PROGRESS": {"type": "phase", "phase": "search"},
                "SEARCH_STALLED": {"type": "phase", "phase": "construct"},
                "CONSTRUCT_TARGETS": {"type": "phase", "phase": "construct"},
                "NEED_LEMMA": {"type": "phase", "phase": "lemma"},
                "AUDIT_REWORK": {"type": "phase", "phase": "lemma"},
                "ORACLE_SUSPECT": {"type": "human_required", "diagnosis": "oracle_batch_integrity"},
                "PROOF_BLOCKED": {"type": "human_required", "diagnosis": "proof_or_budget_exhausted"},
            },
        },
        "actions": [
            _act(
                "solve_precheck",
                label_zh="求解前置校验",
                phases=["gate"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["plan_approved", "kb_fingerprint_fresh"],
                capability_ids=[],
                output_contract_id="solve-precheck-v1",
            ),
            _act(
                "oracle_probe",
                label_zh="Oracle 可信度探测",
                phases=["oracle"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="oracle-probe-v1",
            ),
            _act(
                "closure_ledger",
                label_zh="重建 R 账本",
                phases=["ledger"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="closure-ledger-v1",
            ),
            _act(
                "closure_search",
                label_zh="构造并 Replay 一轮",
                phases=["search"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="closure-search-v1",
            ),
            _act(
                "closure_residual",
                label_zh="轮次分析与路由",
                phases=["residual"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="closure-residual-v1",
            ),
            _act(
                "closure_construct",
                label_zh="基于已发现 key 定向构造",
                phases=["construct"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="closure-construct-v1",
            ),
            _act(
                "closure_explain",
                label_zh="反例维替换解释",
                phases=["construct"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="closure-explain-v1",
            ),
            _act(
                "lemma_leads",
                label_zh="从本轮 reject 生成引理线索",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="lemma-leads-v1",
            ),
            _act(
                "lemma_evidence",
                label_zh="收集引理源码证据包",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="lemma-evidence-v1",
            ),
            _act(
                "lemma_mine",
                label_zh="源码引理挖掘",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="tg-lemma-producer",
                role_id="producer",
                execution_mode="subagent",
                capability_ids=["source-reading", "source-navigation"],
                task_prompt_id="tg/lemma-mine",
                output_contract_id="lemma-mine-v1",
                output_mode="staged",
                staging_contract_id="lemma-mine-staging-v1",
                # Producer staging is finalized by referee, not by apply.
                merge_action_id="lemma_review",
                allowed_write_paths=[
                    "runs/{run_id}/actions/lemma_mine/parts/**",
                    "runs/{run_id}/actions/lemma_mine/scratch/**",
                    "runs/{run_id}/actions/lemma_mine/staging.yaml",
                ],
            ),
            _act(
                "lemma_verify",
                label_zh="引理候选对 R 反证",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="lemma-verify-v1",
                allowed_write_paths=[
                    "runs/{run_id}/actions/lemma_verify/verify.yaml",
                    "tg/closure/lemmas/verify.yaml",
                ],
            ),
            _act(
                "lemma_review",
                label_zh="引理资格审查",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="tg-closure-referee",
                role_id="referee",
                referee_required=True,
                execution_mode="subagent",
                capability_ids=["source-reading"],
                task_prompt_id="tg/lemma-review",
                output_contract_id="lemma-review-v1",
            ),
            _act(
                "lemma_apply",
                label_zh="应用已审引理到 E",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="lemma-apply-v1",
            ),
            _act(
                "lemma_loop",
                label_zh="轮内引理可重入收敛",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="lemma-loop-v1",
                allowed_write_paths=[
                    "tg/closure/lemma_loop.yaml",
                    "tg/closure/rounds/**/lemma.yaml",
                    "runs/{run_id}/actions/lemma_mine/staging.yaml",
                    "runs/{run_id}/actions/lemma_review/review.yaml",
                    "tg/closure/excluded.txt",
                    "tg/closure/excluded_why.csv",
                    "tg/closure/open.txt",
                    "tg/closure/lemmas/active_rules.yaml",
                    "tg/closure/lemmas/reviews.yaml",
                ],
            ),
            _act(
                "closure_audit",
                label_zh="闭环不变量审查",
                phases=["audit"],
                workflow_id="tg-solve",
                agent_id="tg-closure-referee",
                role_id="referee",
                referee_required=True,
                execution_mode="subagent",
                capability_ids=["source-reading"],
                task_prompt_id="tg/closure-audit",
                output_contract_id="closure-audit-v1",
            ),
            _act(
                "closure_certify",
                label_zh="签发 gap=0 证书",
                phases=["certify"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["closure_soundness"],
                capability_ids=[],
                output_contract_id="closure-certify-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
            {"id": "tg-lemma-producer", "role": "producer"},
            {"id": "tg-closure-referee", "role": "referee"},
        ],
        "static_obligations": [
            {"id": "closure_soundness", "label_zh": "TilingKey 闭环健全"},
        ],
        "dynamic_obligation_sources": ["tg/closure/**"],
        "write_roots": ["tg", "runs", "state", "context"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": ["tg/solve", "tg/cases", "tg/closure"],
            "reinit_preserve": [
                "uo",
                "tg/intake",
                "tg/snapshot",
                "tg/contract",
                "tg/realization",
                "tg/init",
                "tg/run.yaml",
                "tg/plan",
                "tg/extract",
            ],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": [
            "gate", "oracle", "ledger", "search", "residual",
            "construct", "lemma", "audit", "certify",
        ],
        "gates": ["plan_approved", "closure_soundness", "kb_fingerprint_fresh"],
    },
    "code-edit": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "git-ops": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "build": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "test-run": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "perf-analyze": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
}
