"""Concrete workflow specs (English ids + Chinese labels)."""

from __future__ import annotations

from typing import Any

# Shared stable policies composed into every semantic / engine action.
DEFAULT_POLICY_IDS: list[str] = [
    "source-authority",
    "code-access",
    "evidence",
    "language",
    "pilot-control",
    "output-quality",
]

# Optional global capabilities merged into every action (prepended, de-duped).
# Keep empty unless a capability is truly universal; prefer per-action lists.
DEFAULT_CAPABILITY_IDS: list[str] = []


def _merge_capability_ids(capability_ids: list[str] | None) -> list[str]:
    """Merge DEFAULT_CAPABILITY_IDS with per-action ids (defaults first, de-duped)."""
    merged: list[str] = []
    for cid in list(DEFAULT_CAPABILITY_IDS) + list(capability_ids or []):
        if cid and cid not in merged:
            merged.append(cid)
    return merged


def _st(sid: str, label_zh: str) -> dict[str, str]:
    return {"id": sid, "label_zh": label_zh}


def _tr(frm: str, to: str, *, kind: str = "forward", reason_codes: list[str] | None = None) -> dict[str, Any]:
    row: dict[str, Any] = {"from": frm, "to": to, "kind": kind}
    if reason_codes:
        row["reason_codes"] = reason_codes
    return row


def _act(
    action_id: str,
    *,
    label_zh: str,
    phases: list[str],
    workflow_id: str,
    checker_required: bool = True,
    referee_required: bool = False,
    gates: list[str] | None = None,
    agent_id: str | None = None,
    role_id: str | None = None,
    execution_mode: str | None = None,
    policy_ids: list[str] | None = None,
    capability_ids: list[str] | None = None,
    action_method_id: str | None = None,
    task_prompt_id: str | None = None,
    context_profile_id: str | None = None,
    output_contract_id: str | None = None,
    output_mode: str | None = None,
    staging_contract_id: str | None = None,
    merge_action_id: str | None = None,
    allowed_write_paths: list[str] | None = None,
    allowed_read_paths: list[str] | None = None,
    forbidden_write_paths: list[str] | None = None,
    forbidden_read_paths: list[str] | None = None,
) -> dict[str, Any]:
    """Declare a Pilot Action with compositional references.

    ``actors`` is derived from ``agent_id`` for authorize / spawn checks.
    Workflow Spec is the sole editable authority for identity fields.
    """
    from ascendc_pilot.ownership import (
        ACTION_FORBIDDEN_READ_PATHS,
        ACTION_FINALIZER_WRITE_PATHS,
        ACTION_PRODUCER_WRITE_PATHS,
        ACTION_READ_PATHS,
        ACTION_WRITE_PATHS,
        infer_execution_mode,
    )

    method_id = action_method_id or f"{workflow_id}/{action_id.replace('_', '-')}"
    actors = [agent_id] if agent_id else []
    mode = infer_execution_mode(
        agent_id=agent_id,
        role_id=role_id,
        execution_mode=execution_mode,
    )
    writes = allowed_write_paths
    if writes is None:
        if output_mode == "staged" and role_id == "producer":
            writes = list((ACTION_PRODUCER_WRITE_PATHS.get(workflow_id) or {}).get(action_id) or [])
        if not writes:
            writes = list((ACTION_WRITE_PATHS.get(workflow_id) or {}).get(action_id) or [])
    reads = allowed_read_paths
    if reads is None:
        reads = list((ACTION_READ_PATHS.get(workflow_id) or {}).get(action_id) or [])
    forbid_reads = forbidden_read_paths
    if forbid_reads is None:
        forbid_reads = list((ACTION_FORBIDDEN_READ_PATHS.get(workflow_id) or {}).get(action_id) or [])
    # Staged producers must not write finalizer canonical paths.
    forbid_writes = list(forbidden_write_paths or [])
    if output_mode == "staged" and role_id == "producer":
        for p in (ACTION_FINALIZER_WRITE_PATHS.get(workflow_id) or {}).get(action_id) or []:
            if p not in forbid_writes:
                forbid_writes.append(p)
    row: dict[str, Any] = {
        "id": action_id,
        "label_zh": label_zh,
        "phases": list(phases),
        "checker_required": checker_required,
        "referee_required": referee_required,
        "gates": list(gates or []),
        "agent_id": agent_id,
        "role_id": role_id,
        "execution_mode": mode,
        "policy_ids": list(policy_ids if policy_ids is not None else DEFAULT_POLICY_IDS),
        "capability_ids": _merge_capability_ids(capability_ids),
        "action_method_id": method_id,
        "task_prompt_id": task_prompt_id,
        "context_profile_id": context_profile_id or f"{workflow_id}-{action_id.replace('_', '-')}",
        "output_contract_id": output_contract_id,
        "allowed_write_paths": list(writes or []),
        "allowed_read_paths": list(reads or []),
        "forbidden_write_paths": list(forbid_writes),
        "forbidden_read_paths": list(forbid_reads or []),
        # Derived for authorize / Task spawn (single primary actor).
        "actors": actors,
    }
    if output_mode:
        row["output_mode"] = output_mode
    if staging_contract_id:
        row["staging_contract_id"] = staging_contract_id
    if merge_action_id:
        row["merge_action_id"] = merge_action_id
    return row


_UO_INIT_RESOLVE_GATES = [
    "key_triage_required",
    "key_resolve_receipt",
    "empty_only_producer",
    "confidence_gate",
    "key_report_quality",
    "confidence_closed_high",
    "confidence_reason_review",
]

# Static obligation id → gate id that settles it when that gate passes.
STATIC_OBLIGATION_GATE_MAP: dict[str, str] = {
    "scope_confirmed": "scope_receipt",
    "uo_product_ready": "uo_product_ready",
    "kb_integrity_passed": "integrity",
    "kb_review_passed": "kb_review",
    "kb_ready": "kb_ready",
    "uo_ready": "uo_ready",
    "init_confirmed": "init_confirmed",
    "plan_approved": "plan_approved",
    "solve_terminal": "solve_terminal",
    "closure_soundness": "closure_soundness",
}

CLOSED_OBLIGATION_STATUSES = frozenset(
    {
        "resolved",
        "verified",
        "not_applicable",
        "human_required",
        "rejected",
    }
)

_CAPS_CODE = ["source-reading", "source-navigation", "kb-query"]
_CAPS_EXTRACT = [
    "source-reading",
    "source-navigation",
    "kb-query",
    "semantic-resolution",
    "structured-ir-query",
    "readonly-source-search",
    "action-scratch",
    "sharded-llm-producer",
    "bounded-semantic-batch",
    "producer-self-check",
]
_CAPS_ADJUDICATE = [
    "source-reading",
    "source-navigation",
    "kb-query",
    "semantic-resolution",
    "structured-ir-query",
    "readonly-source-search",
    "action-scratch",
    "sharded-semantic-producer",
    "sharded-llm-producer",
    "bounded-semantic-batch",
    "producer-self-check",
]
_CAPS_RESOLVE = [
    "source-reading",
    "source-navigation",
    "kb-query",
    "semantic-resolution",
    "action-scratch",
    "sharded-llm-producer",
    "bounded-semantic-batch",
    "producer-self-check",
]
_CAPS_REVIEW = ["kb-query"]
_CAPS_CONTRACT = ["contract-building", "kb-query"]
_CAPS_OBLIGATION = ["kb-query"]

WORKFLOWS: dict[str, dict[str, Any]] = {
    "uo-init": {
        "slash": "/uo-init",
        "engine": "uo",
        "entry_state": "prepare",
        "terminal_ready_states": ["review"],
        "retry_budget": 3,
        "states": [
            _st("prepare", "准备 BuildVariant / 范围"),
            _st("extract", "Clang 抽取 CompilerFacts"),
            _st("analyze", "确定性 CodeMap Pass"),
            _st("resolve", "语义缺口消解"),
            _st("commit", "写入 operator.uo"),
            _st("review", "结构一致性审查"),
        ],
        "transitions": [
            _tr("prepare", "extract"),
            _tr("extract", "analyze"),
            _tr("analyze", "resolve"),
            _tr("resolve", "commit"),
            _tr("commit", "review"),
            _tr("extract", "prepare", kind="rework", reason_codes=["SCOPE_REWORK", "SCOPE_FAILED"]),
            _tr("analyze", "extract", kind="rework", reason_codes=["EXTRACT_REWORK"]),
            _tr("commit", "analyze", kind="rework", reason_codes=["INTEGRITY_REWORK", "GAP_REWORK"]),
            _tr("review", "analyze", kind="rework", reason_codes=["KB_REVIEW_REWORK"]),
            _tr("review", "commit", kind="rework", reason_codes=["export_kb", "integrity"]),
            _tr("review", "prepare", kind="rework", reason_codes=["scope", "SCOPE_REWORK"]),
        ],
        "phase_gates": {
            "prepare": ["layout_receipt"],
            "extract": ["extract_receipt"],
            "analyze": [],
            "resolve": ["normalize_receipt"],
            "commit": ["uo_product_ready", "integrity"],
            "review": ["kb_review"],
        },
        "pipelines": {
            "prepare": ["prepare"],
            "extract": ["extract"],
            "analyze": ["analyze"],
            "resolve": ["resolve", "apply_gap_patch"],
            "commit": ["commit"],
            "review": ["review"],
        },
        "complete_gates": [
            "extract_receipt",
            "uo_product_ready",
            "integrity",
            "kb_review",
        ],
        "meta": {
            "max_gap_resolve_attempts": 3,
            "product": "codemap-uo",
            "recovery_by_reason": {
                "SCOPE_REWORK": {
                    "type": "transition",
                    "target_phase": "prepare",
                    "next_action": "prepare",
                },
                "EXTRACT_REWORK": {"type": "action", "action_id": "extract"},
                "GAP_REWORK": {"type": "action", "action_id": "resolve"},
                "INTEGRITY_REWORK": {"type": "action", "action_id": "commit"},
                "KB_REVIEW_REWORK": {"type": "action", "action_id": "review"},
            },
        },
        "actions": [
            _act(
                "prepare",
                label_zh="准备范围与 BuildVariant",
                phases=["prepare"],
                workflow_id="uo-init",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                gates=["layout_receipt"],
                capability_ids=["source-navigation", "source-reading"],
                task_prompt_id="uo/scope-confirmation",
                output_contract_id="uo-prepare-v1",
            ),
            _act(
                "extract",
                label_zh="Clang 抽取 CompilerFacts",
                phases=["extract"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["extract_receipt"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="uo-extract-v1",
            ),
            _act(
                "analyze",
                label_zh="确定性 CodeMap Pass",
                phases=["analyze"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="uo-analyze-v1",
            ),
            _act(
                "resolve",
                label_zh="消解语义缺口",
                phases=["resolve"],
                workflow_id="uo-init",
                agent_id="uo-semantic-resolver",
                role_id="producer",
                execution_mode="subagent",
                gates=["gap_patch_evidence"],
                capability_ids=_CAPS_RESOLVE,
                task_prompt_id="uo/resolve-gaps",
                output_contract_id="resolve-gaps-v1",
                output_mode="staged",
                staging_contract_id="resolve-gaps-staging-v1",
                merge_action_id="apply_gap_patch",
                allowed_write_paths=[
                    "runs/{run_id}/actions/resolve_gaps/parts/**",
                    "runs/{run_id}/actions/resolve_gaps/scratch/**",
                    "runs/{run_id}/actions/resolve_gaps/staging.yaml",
                    "runs/{run_id}/actions/resolve/parts/**",
                    "runs/{run_id}/actions/resolve/scratch/**",
                    "runs/{run_id}/actions/resolve/staging.yaml",
                ],
            ),
            _act(
                "apply_gap_patch",
                label_zh="合并 gap patch（resolve merge）",
                phases=["resolve"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["normalize_receipt"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="gap-patch-v1",
            ),
            _act(
                "commit",
                label_zh="写入 operator.uo CodeMap",
                phases=["commit"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["uo_product_ready", "integrity"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="uo-commit-v1",
            ),
            _act(
                "review",
                label_zh="CodeMap 结构审查",
                phases=["review"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                referee_required=False,
                gates=["kb_review"],
                capability_ids=_CAPS_REVIEW,
                task_prompt_id="uo/kb-review",
                output_contract_id="uo-review-v1",
            ),
        ],
        "agents": [
            {"id": "uo-semantic-resolver", "role": "producer"},
            {"id": "deterministic-uo-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [
            {"id": "scope_confirmed", "label_zh": "范围已确认"},
            {"id": "uo_product_ready", "label_zh": "operator.uo 已写入"},
            {"id": "kb_review_passed", "label_zh": "产物审查通过"},
        ],
        "dynamic_obligation_sources": ["ir/unresolved.yaml"],
        "write_roots": ["uo", "runs", "state", "context"],
        "reset_policy": {
            "reinit_delete": ["uo"],
            "reinit_preserve": [],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["prepare", "extract", "analyze", "resolve", "commit", "review"],
        "gates": [
            "layout_receipt",
            "extract_receipt",
            "normalize_receipt",
            "gap_patch_evidence",
            "uo_product_ready",
            "integrity",
            "kb_review",
        ],
    },
    "uo-update": {
        "slash": "/uo-update",
        "engine": "uo",
        "entry_state": "detect",
        "terminal_ready_states": ["diff"],
        "retry_budget": 3,
        "states": [
            _st("detect", "变更检测"),
            _st("plan", "更新计划"),
            _st("apply", "应用变更"),
            _st("resolve", "语义闭合"),
            _st("export", "导出与校验"),
            _st("diff", "差异摘要"),
        ],
        "transitions": [
            _tr("detect", "plan"),
            _tr("plan", "apply"),
            _tr("apply", "resolve"),
            _tr("resolve", "export"),
            _tr("export", "diff"),
            _tr("resolve", "resolve", kind="rework", reason_codes=["KEY_REWORK", "CONFIDENCE_REWORK"]),
            _tr("export", "resolve", kind="rework", reason_codes=["INTEGRITY_REWORK", "residual_resolve", "input_derivable"]),
            _tr(
                "export",
                "apply",
                kind="rework",
                reason_codes=["EXTRACT_REWORK", "entrypoints", "extract_plan"],
            ),
            _tr("detect", "diff", kind="forward", reason_codes=["DIFF_ONLY"]),
        ],
        "phase_gates": {
            # key_triage LLM chain deferred on new KB — stubs + confidence/integrity only
            "resolve": ["confidence_gate"],
            "export": ["integrity"],
        },
        "pipelines": {
            "detect": ["detect_changes"],
            "plan": ["plan_update"],
            "apply": ["apply_update"],
            "resolve": [
                "key_triage",
                "key_resolution",
                "confidence_report",
                "confidence_review",
            ],
            "export": ["export_integrity"],
            "diff": ["diff_summary"],
        },
        "complete_gates": [
            "confidence_gate",
            "integrity",
        ],
        "complete_gates_diff_only": [],
        "actions": [
            _act(
                "detect_changes",
                label_zh="检测源码变更",
                phases=["detect"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=["source-reading"],
                output_contract_id="change-detect-v1",
            ),
            _act(
                "plan_update",
                label_zh="制定更新计划",
                phases=["plan"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=["source-reading", "kb-query"],
                output_contract_id="update-plan-v1",
            ),
            _act(
                "apply_update",
                label_zh="应用变更",
                phases=["apply"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=["source-reading", "kb-query"],
                output_contract_id="update-apply-v1",
            ),
            _act(
                "key_triage",
                label_zh="KEY 粗分（新 KB stub）",
                phases=["resolve"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                action_method_id="uo-update/key-triage",
                task_prompt_id=None,
                output_contract_id="key-triage-v1",
            ),
            _act(
                "key_resolution",
                label_zh="KEY 语义闭合（新 KB stub）",
                phases=["resolve"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                action_method_id="uo-update/key-resolution",
                task_prompt_id=None,
                output_contract_id="input-derivable-patch-v1",
            ),
            _act(
                "confidence_report",
                label_zh="生成置信度报告",
                phases=["resolve"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["confidence_gate"],
                capability_ids=[],
                output_contract_id="confidence-report-v1",
            ),
            _act(
                "confidence_review",
                label_zh="置信度原因审查（新 KB stub）",
                phases=["resolve"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                action_method_id="uo-update/confidence-review",
                task_prompt_id=None,
                output_contract_id="confidence-reason-review-v1",
            ),
            _act(
                "export_integrity",
                label_zh="导出与完整性校验",
                phases=["export"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["integrity"],
                capability_ids=[],
                output_contract_id="integrity-v1",
            ),
            _act(
                "diff_summary",
                label_zh="只读差异摘要",
                phases=["diff", "detect"],
                workflow_id="uo-update",
                checker_required=False,
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=["kb-query"],
                output_contract_id="diff-summary-v1",
            ),
            _act(
                "diff_only",
                label_zh="仅差异摘要（跳过完整更新）",
                phases=["detect", "diff"],
                workflow_id="uo-update",
                checker_required=False,
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=["kb-query"],
                output_contract_id="diff-summary-v1",
            ),
        ],
        "agents": [
            {"id": "uo-semantic-resolve", "role": "producer"},
            {"id": "uo-key-resolve", "role": "producer"},
            {"id": "uo-confidence-review", "role": "referee"},
            {"id": "uo-kb-review", "role": "referee"},
            {"id": "deterministic-uo-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [{"id": "kb_integrity_passed", "label_zh": "完整性通过"}],
        "dynamic_obligation_sources": ["ir/unresolved.yaml", "ir/input_derivable_gaps.yaml"],
        "write_roots": ["uo", "runs", "state", "context"],
        "reset_policy": {
            "reinit_delete": [
                "uo/diff",
                "uo/summary/update_plan.yaml",
            ],
            "reinit_preserve": ["uo"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["detect", "plan", "apply", "resolve", "export", "diff"],
        "gates": [
            "confidence_gate",
            "integrity",
        ],
    },
    "uo-query": {
        "slash": "/uo-query",
        "engine": "uo",
        "entry_state": "route",
        "terminal_ready_states": ["answer"],
        "retry_budget": 3,
        "states": [
            _st("route", "问题路由"),
            _st("lookup", "知识检索"),
            _st("answer", "回答"),
        ],
        "transitions": [
            _tr("route", "lookup"),
            _tr("lookup", "answer"),
            _tr("lookup", "lookup", kind="rework", reason_codes=["LOOKUP_REWORK"]),
        ],
        "phase_gates": {"route": ["kb_ready"]},
        "complete_gates": ["kb_ready"],
        "actions": [
            _act(
                "kb_lookup",
                label_zh="KB 查询",
                phases=["route", "lookup", "answer"],
                workflow_id="uo-query",
                agent_id="uo-query",
                role_id="readonly_analyst",
                gates=["kb_ready"],
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                task_prompt_id="uo/kb-lookup",
                output_contract_id="kb-answer-v1",
            ),
        ],
        "agents": [{"id": "uo-query", "role": "readonly_analyst"}],
        "static_obligations": [{"id": "kb_ready", "label_zh": "KB 就绪"}],
        "dynamic_obligation_sources": [],
        "write_roots": ["runs", "context", "memory"],
        "reset_policy": {
            "reinit_delete": [],
            "reinit_preserve": ["uo", "tg", "ce"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["route", "lookup", "answer"],
        "gates": ["kb_ready"],
    },
    "ce-review": {
        "slash": "/ce-review",
        "engine": "ce",
        "entry_state": "context",
        "terminal_ready_states": ["summary"],
        "retry_budget": 3,
        "states": [
            _st("context", "组装上下文"),
            _st("bug", "缺陷审查"),
            _st("functional", "功能审查"),
            _st("summary", "汇总"),
        ],
        "transitions": [
            _tr("context", "bug"),
            _tr("bug", "functional"),
            _tr("functional", "summary"),
        ],
        "phase_gates": {"context": ["kb_ready", "context_pack"]},
        "complete_gates": ["kb_ready", "context_pack"],
        "actions": [
            _act(
                "code_review",
                label_zh="代码审查",
                phases=["context", "bug", "functional", "summary"],
                workflow_id="ce-review",
                agent_id="ce-reviewer",
                role_id="readonly_reviewer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                task_prompt_id="ce/code-review",
                output_contract_id="code-review-v1",
            ),
        ],
        "agents": [{"id": "ce-reviewer", "role": "readonly_reviewer"}],
        "static_obligations": [{"id": "kb_ready", "label_zh": "KB 就绪"}],
        "dynamic_obligation_sources": [],
        "write_roots": ["ce/review", "runs", "context"],
        "reset_policy": {
            "reinit_delete": ["ce/review"],
            "reinit_preserve": ["uo", "tg"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["context", "bug", "functional", "summary"],
        "gates": ["kb_ready", "context_pack"],
    },
    "tg-init": {
        "slash": "/tg-init",
        "engine": "tg",
        "entry_state": "intent",
        "terminal_ready_states": ["confirm"],
        "retry_budget": 3,
        # Base = tilingkey_full_coverage (no CSV merge/nest). csv_consumer via overlay.
        "states": [
            _st("intent", "意图确认"),
            _st("kb_ready", "KB 检查"),
            _st("contract", "合同构建"),
            _st("bind", "Host 视图绑定"),
            _st("gate", "完整性校验"),
            _st("confirm", "人工确认"),
        ],
        "transitions": [
            _tr("intent", "kb_ready"),
            _tr("kb_ready", "contract"),
            _tr("contract", "bind"),
            _tr("bind", "gate"),
            _tr("gate", "confirm"),
            _tr("gate", "bind", kind="rework", reason_codes=["BIND_REWORK"]),
            _tr("confirm", "gate", kind="rework", reason_codes=["AUDIT_REWORK"]),
        ],
        "phase_gates": {
            "kb_ready": ["uo_ready", "input_derivable_closed"],
            "bind": ["tilingkey_binding_ready"],
            "gate": ["audit_pass"],
            "confirm": ["init_confirmed", "kb_fingerprint_fresh"],
        },
        "complete_gates": [
            "uo_ready",
            "input_derivable_closed",
            "tilingkey_binding_ready",
            "audit_pass",
            "init_confirmed",
            "kb_fingerprint_fresh",
        ],
        "actions": [
            _act(
                "init_intent",
                label_zh="确认 TG 模式意图",
                phases=["intent"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-init-intent-v1",
            ),
            _act(
                "kb_check",
                label_zh="校验定稿 KB",
                phases=["kb_ready"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["uo_ready", "input_derivable_closed"],
                capability_ids=["kb-query"],
                output_contract_id="uo-ready-v1",
            ),
            _act(
                "contract_build",
                label_zh="构建合同骨架",
                phases=["contract"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=_CAPS_CONTRACT,
                output_contract_id="tilingkey-contract-v1",
            ),
            _act(
                "semantic_bind",
                label_zh="语义绑定",
                phases=["bind"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["tilingkey_binding_ready"],
                capability_ids=["kb-query", "semantic-resolution"],
                output_contract_id="tilingkey-binding-v1",
            ),
            # CSV-only actions (activated by csv_consumer overlay phases).
            _act(
                "bind_merge",
                label_zh="绑定合并",
                phases=["merge"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["merge_pass"],
                capability_ids=[],
                output_contract_id="bind-merge-v1",
            ),
            _act(
                "mid_nest",
                label_zh="中间量闭合",
                phases=["nest"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="mid-nest-v1",
            ),
            _act(
                "integrity_gate",
                label_zh="完整性校验",
                phases=["gate"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=[],
                capability_ids=[],
                output_contract_id="tilingkey-integrity-v1",
            ),
            _act(
                "init_audit",
                label_zh="Init 审计",
                phases=["gate"],
                workflow_id="tg-init",
                agent_id="tg-init-audit",
                role_id="referee",
                referee_required=True,
                gates=["audit_pass"],
                capability_ids=_CAPS_REVIEW,
                task_prompt_id="tg/init-audit",
                output_contract_id="init-audit-v1",
            ),
            _act(
                "human_confirm",
                label_zh="人工确认",
                phases=["confirm"],
                workflow_id="tg-init",
                agent_id=None,
                role_id=None,
                gates=["init_confirmed", "kb_fingerprint_fresh"],
                capability_ids=[],
                task_prompt_id="tg/human-confirm",
                output_contract_id="init-confirmed-v1",
            ),
        ],
        "agents": [
            {"id": "tg-semantic-bind", "role": "producer"},
            {"id": "tg-init-audit", "role": "referee"},
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [
            {"id": "uo_ready", "label_zh": "UO KB 就绪"},
            {"id": "init_confirmed", "label_zh": "Init 已确认"},
        ],
        "dynamic_obligation_sources": [
            "realization/unresolved.yaml",
            "realization/binding_gaps.yaml",
        ],
        "write_roots": ["tg", "runs", "state", "context"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": ["tg"],
            "reinit_preserve": ["uo"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["intent", "kb_ready", "contract", "bind", "gate", "confirm"],
        "gates": [
            "uo_ready",
            "kb_fingerprint_fresh",
            "tilingkey_binding_ready",
            "audit_pass",
            "init_confirmed",
        ],
        "meta": {"default_mode": "tilingkey_full_coverage"},
        "mode_overlays": {
            "tilingkey_full_coverage": {
                "phases": ["intent", "kb_ready", "contract", "bind", "gate", "confirm"],
                "states": [
                    _st("intent", "意图确认"),
                    _st("kb_ready", "KB 检查"),
                    _st("contract", "合同构建"),
                    _st("bind", "Host 视图绑定"),
                    _st("gate", "完整性校验"),
                    _st("confirm", "人工确认"),
                ],
                "transitions": [
                    _tr("intent", "kb_ready"),
                    _tr("kb_ready", "contract"),
                    _tr("contract", "bind"),
                    _tr("bind", "gate"),
                    _tr("gate", "confirm"),
                    _tr("gate", "bind", kind="rework", reason_codes=["BIND_REWORK"]),
                    _tr("confirm", "gate", kind="rework", reason_codes=["AUDIT_REWORK"]),
                ],
                "phase_gates": {
                    "kb_ready": ["uo_ready", "input_derivable_closed"],
                    "bind": ["tilingkey_binding_ready"],
                    "gate": ["audit_pass"],
                    "confirm": ["init_confirmed", "kb_fingerprint_fresh"],
                },
                "complete_gates": [
                    "uo_ready",
                    "input_derivable_closed",
                    "tilingkey_binding_ready",
                    "audit_pass",
                    "init_confirmed",
                    "kb_fingerprint_fresh",
                ],
                "pipelines": {
                    "intent": ["init_intent"],
                    "kb_ready": ["kb_check"],
                    "contract": ["contract_build"],
                    "bind": ["semantic_bind"],
                    "gate": ["integrity_gate", "init_audit"],
                    "confirm": ["human_confirm"],
                },
                "gates": [
                    "uo_ready",
                    "kb_fingerprint_fresh",
                    "tilingkey_binding_ready",
                    "audit_pass",
                    "init_confirmed",
                ],
                "action_overrides": {
                    "contract_build": {"output_contract_id": "tilingkey-contract-v1"},
                    "semantic_bind": {
                        "output_contract_id": "tilingkey-binding-v1",
                        "agent_id": "deterministic-tg-engine",
                        "role_id": "deterministic_engine",
                        "gates": ["tilingkey_binding_ready"],
                        "task_prompt_id": None,
                        "output_mode": None,
                        "staging_contract_id": None,
                        "merge_action_id": None,
                        "allowed_write_paths": [
                            "tg/realization/binding_inventory.yaml",
                        ],
                    },
                    "integrity_gate": {
                        "output_contract_id": "tilingkey-integrity-v1",
                        "gates": [],
                    },
                    "human_confirm": {
                        "allowed_write_paths": [
                            "tg/init/status.yaml",
                            "tg/init/kb_fingerprint.yaml",
                            "tg/init/confirmation.yaml",
                        ],
                    },
                },
            },
            "csv_consumer": {
                "phases": [
                    "intent",
                    "kb_ready",
                    "contract",
                    "bind",
                    "merge",
                    "nest",
                    "gate",
                    "confirm",
                ],
                "states": [
                    _st("intent", "意图确认"),
                    _st("kb_ready", "KB 检查"),
                    _st("contract", "合同构建"),
                    _st("bind", "语义绑定"),
                    _st("merge", "绑定合并"),
                    _st("nest", "中间量闭合"),
                    _st("gate", "完整性校验"),
                    _st("confirm", "人工确认"),
                ],
                "transitions": [
                    _tr("intent", "kb_ready"),
                    _tr("kb_ready", "contract"),
                    _tr("contract", "bind"),
                    _tr("bind", "merge"),
                    _tr("merge", "nest"),
                    _tr("nest", "gate"),
                    _tr("gate", "confirm"),
                    _tr("merge", "bind", kind="rework", reason_codes=["BIND_REWORK"]),
                    _tr("gate", "merge", kind="rework", reason_codes=["MERGE_REWORK"]),
                    _tr("confirm", "gate", kind="rework", reason_codes=["AUDIT_REWORK"]),
                ],
                "phase_gates": {
                    "kb_ready": ["uo_ready", "input_derivable_closed"],
                    "bind": ["bind_progress"],
                    "merge": ["merge_pass"],
                    "nest": ["family_path_obligation"],
                    "gate": ["audit_pass", "family_path_obligation"],
                    "confirm": ["init_confirmed", "kb_fingerprint_fresh"],
                },
                "complete_gates": [
                    "uo_ready",
                    "input_derivable_closed",
                    "family_path_obligation",
                    "merge_pass",
                    "audit_pass",
                    "init_confirmed",
                    "kb_fingerprint_fresh",
                ],
                "pipelines": {
                    "intent": ["init_intent"],
                    "kb_ready": ["kb_check"],
                    "contract": ["contract_build"],
                    "bind": ["semantic_bind"],
                    "merge": ["bind_merge"],
                    "nest": ["mid_nest"],
                    "gate": ["integrity_gate", "init_audit"],
                    "confirm": ["human_confirm"],
                },
                "gates": [
                    "uo_ready",
                    "kb_fingerprint_fresh",
                    "bind_progress",
                    "merge_pass",
                    "domain_symmetry",
                    "csv_closure",
                    "audit_pass",
                    "init_confirmed",
                ],
                "action_overrides": {
                    "contract_build": {"output_contract_id": "csv-contract-v1"},
                    "semantic_bind": {
                        "output_contract_id": "semantic-bind-v1",
                        "agent_id": "tg-semantic-bind",
                        "role_id": "producer",
                        "gates": ["bind_progress"],
                        "task_prompt_id": "tg/semantic-bind",
                        "output_mode": "staged",
                        "staging_contract_id": "semantic-bind-patch-v1",
                        "merge_action_id": "semantic_bind",
                        "allowed_write_paths": [
                            "tg/realization/semantic_bind_patch.yaml",
                        ],
                    },
                    "integrity_gate": {
                        "output_contract_id": "tg-integrity-v1",
                        "gates": ["domain_symmetry", "csv_closure"],
                    },
                    "human_confirm": {
                        "allowed_write_paths": [
                            "tg/init/status.yaml",
                            "tg/init/kb_fingerprint.yaml",
                            "tg/realization/domain_review.yaml",
                            "tg/realization/binding_lexicon.yaml",
                        ],
                    },
                },
            },
        },
    },
    "tg-plan": {
        "slash": "/tg-plan",
        "engine": "tg",
        "entry_state": "intent",
        "terminal_ready_states": ["approve"],
        "retry_budget": 3,
        "states": [
            _st("intent", "规划意图"),
            _st("scope", "规划范围"),
            _st("gate", "前置门禁"),
            _st("build", "生成义务"),
            _st("filter", "过滤裁剪"),
            _st("review", "规划审查"),
            _st("approve", "人工批准"),
        ],
        "transitions": [
            _tr("intent", "scope"),
            _tr("scope", "gate"),
            _tr("gate", "build"),
            _tr("build", "filter"),
            _tr("filter", "review"),
            _tr("review", "approve"),
            _tr("approve", "review", kind="rework", reason_codes=["PLAN_REWORK"]),
        ],
        "phase_gates": {
            "gate": ["tg_init_confirmed", "kb_fingerprint_fresh"],
            "approve": ["plan_approved"],
        },
        "complete_gates": ["tg_init_confirmed", "plan_approved"],
        "actions": [
            _act(
                "plan_intent",
                label_zh="确认规划意图",
                phases=["intent"],
                workflow_id="tg-plan",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                capability_ids=[],
                task_prompt_id="tg/plan-intent",
                output_contract_id="plan-intent-v1",
            ),
            _act(
                "plan_scope",
                label_zh="确定规划范围",
                phases=["scope"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=_CAPS_OBLIGATION,
                output_contract_id="plan-scope-v1",
            ),
            _act(
                "plan_precheck",
                label_zh="规划前置门禁",
                phases=["gate"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["tg_init_confirmed", "kb_fingerprint_fresh"],
                capability_ids=[],
                output_contract_id="plan-precheck-v1",
            ),
            _act(
                "plan_build",
                label_zh="生成覆盖义务",
                phases=["build", "filter", "review"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=_CAPS_OBLIGATION,
                output_contract_id="plan-build-v1",
            ),
            _act(
                "plan_approve",
                label_zh="批准规划",
                phases=["approve"],
                workflow_id="tg-plan",
                agent_id=None,
                role_id=None,
                gates=["plan_approved"],
                capability_ids=[],
                task_prompt_id="tg/plan-approve",
                output_contract_id="plan-approved-v1",
            ),
        ],
        "agents": [
            {"id": "ascendc-pilot", "role": "controller"},
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [{"id": "plan_approved", "label_zh": "规划已批准"}],
        "dynamic_obligation_sources": ["plan/**/uncovered_obligations.yaml"],
        "write_roots": ["tg", "runs", "state", "context"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": ["tg"],
            "reinit_preserve": ["uo"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["intent", "scope", "gate", "build", "filter", "review", "approve"],
        "gates": ["tg_init_confirmed", "plan_approved"],
    },
    "tg-solve": {
        "slash": "/tg-solve",
        "engine": "tg",
        "entry_state": "gate",
        "terminal_ready_states": ["certify"],
        "retry_budget": 8,
        "states": [
            _st("gate", "求解前置"),
            _st("oracle", "Oracle 探测"),
            _st("ledger", "重建账本"),
            _st("search", "定向搜索一轮"),
            _st("residual", "残差路由"),
            _st("construct", "构造式收尾"),
            _st("lemma", "引理封口"),
            _st("audit", "闭环审查"),
            _st("certify", "签发证书"),
            # csv_consumer 兼容相位（mode_overlays 选用；默认不走）
            _st("encode", "编码约束"),
            _st("solve", "Z3 求解"),
            _st("project", "CSV 投影"),
            _st("cover", "覆盖确认"),
        ],
        "transitions": [
            _tr("gate", "oracle"),
            _tr("oracle", "ledger"),
            _tr("ledger", "search"),
            _tr("search", "residual"),
            _tr("residual", "audit"),
            _tr("audit", "certify"),
            _tr("construct", "residual"),
            _tr("lemma", "ledger"),
            # residual 回边：search / construct / lemma（由 route reason 驱动 acp rework）
            _tr("residual", "search", kind="rework", reason_codes=["SEARCH_PROGRESS"]),
            _tr("residual", "construct", kind="rework", reason_codes=["CONSTRUCT_TARGETS"]),
            _tr("residual", "lemma", kind="rework", reason_codes=["NEED_LEMMA", "SEARCH_STALLED"]),
            _tr("audit", "lemma", kind="rework", reason_codes=["AUDIT_REWORK", "LEMMA_REWORK"]),
            # csv_consumer 路径（仅 csv_consumer overlay 激活）
            _tr("gate", "encode"),
            _tr("encode", "solve"),
            _tr("solve", "project"),
            _tr("project", "cover"),
            _tr("solve", "encode", kind="rework", reason_codes=["SOLVE_REWORK"]),
        ],
        "phase_gates": {
            "gate": ["plan_approved", "kb_fingerprint_fresh"],
            "certify": ["closure_soundness"],
            "cover": ["solve_terminal"],
        },
        "complete_gates": ["plan_approved", "closure_soundness"],
        "mode_overlays": {
            "tilingkey_full_coverage": {
                "terminal_ready_states": ["certify"],
                "complete_gates": ["plan_approved", "closure_soundness"],
                "transitions": [
                    _tr("gate", "oracle"),
                    _tr("oracle", "ledger"),
                    _tr("ledger", "search"),
                    _tr("search", "residual"),
                    _tr("residual", "audit"),
                    _tr("audit", "certify"),
                    _tr("construct", "residual"),
                    _tr("lemma", "ledger"),
                    _tr("residual", "search", kind="rework", reason_codes=["SEARCH_PROGRESS"]),
                    _tr("residual", "construct", kind="rework", reason_codes=["CONSTRUCT_TARGETS"]),
                    _tr("residual", "lemma", kind="rework", reason_codes=["NEED_LEMMA", "SEARCH_STALLED"]),
                    _tr("audit", "lemma", kind="rework", reason_codes=["AUDIT_REWORK", "LEMMA_REWORK"]),
                ],
                "pipelines": {
                    "gate": ["solve_precheck"],
                    "oracle": ["oracle_probe"],
                    "ledger": ["closure_ledger"],
                    "search": ["closure_search"],
                    "residual": ["closure_residual"],
                    "construct": ["closure_construct", "closure_explain"],
                    "lemma": [
                        "lemma_leads",
                        "lemma_evidence",
                        "lemma_mine",
                        "lemma_verify",
                        "lemma_review",
                        "lemma_apply",
                        "lemma_loop",
                    ],
                    "audit": ["closure_audit"],
                    "certify": ["closure_certify"],
                },
            },
            "csv_consumer": {
                "terminal_ready_states": ["cover"],
                "complete_gates": ["plan_approved", "solve_terminal", "domain_symmetry"],
                "transitions": [
                    _tr("gate", "encode"),
                    _tr("encode", "solve"),
                    _tr("solve", "project"),
                    _tr("project", "cover"),
                    _tr("solve", "encode", kind="rework", reason_codes=["SOLVE_REWORK"]),
                ],
                "pipelines": {
                    "gate": ["solve_precheck"],
                    "encode": ["z3_solve"],
                    "solve": ["z3_solve"],
                    "project": ["z3_solve"],
                    "cover": ["cover_confirm"],
                },
            },
        },
        "meta": {
            "default_mode": "tilingkey_full_coverage",
            "capability_ids": [],
            "recovery_by_reason": {
                "SEARCH_PROGRESS": {"type": "phase", "phase": "search"},
                "SEARCH_STALLED": {"type": "phase", "phase": "lemma"},
                "CONSTRUCT_TARGETS": {"type": "phase", "phase": "construct"},
                "NEED_LEMMA": {"type": "phase", "phase": "lemma"},
                "AUDIT_REWORK": {"type": "phase", "phase": "lemma"},
                "ORACLE_SUSPECT": {"type": "human_required", "diagnosis": "oracle_batch_integrity"},
                "PROOF_BLOCKED": {"type": "human_required", "diagnosis": "proof_or_budget_exhausted"},
            },
        },
        "actions": [
            _act(
                "solve_precheck",
                label_zh="求解前置校验",
                phases=["gate"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["plan_approved", "kb_fingerprint_fresh"],
                capability_ids=[],
                output_contract_id="solve-precheck-v1",
            ),
            _act(
                "oracle_probe",
                label_zh="Oracle 可信度探测",
                phases=["oracle"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="oracle-probe-v1",
            ),
            _act(
                "closure_ledger",
                label_zh="重建 R 账本",
                phases=["ledger"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="closure-ledger-v1",
            ),
            _act(
                "closure_search",
                label_zh="定向搜索一轮",
                phases=["search"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="closure-search-v1",
            ),
            _act(
                "closure_residual",
                label_zh="残差分析与路由",
                phases=["residual"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="closure-residual-v1",
            ),
            _act(
                "closure_construct",
                label_zh="构造式收尾",
                phases=["construct"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="closure-construct-v1",
            ),
            _act(
                "closure_explain",
                label_zh="反例维替换解释",
                phases=["construct"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="closure-explain-v1",
            ),
            _act(
                "lemma_leads",
                label_zh="生成引理线索包",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="lemma-leads-v1",
            ),
            _act(
                "lemma_evidence",
                label_zh="收集引理源码证据包",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="lemma-evidence-v1",
            ),
            _act(
                "lemma_mine",
                label_zh="源码引理挖掘",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="tg-lemma-producer",
                role_id="producer",
                execution_mode="subagent",
                capability_ids=["source-reading", "source-navigation"],
                task_prompt_id="tg/lemma-mine",
                output_contract_id="lemma-mine-v1",
                output_mode="staged",
                staging_contract_id="lemma-mine-staging-v1",
                # Producer staging is finalized by referee, not by apply.
                merge_action_id="lemma_review",
                allowed_write_paths=[
                    "runs/{run_id}/actions/lemma_mine/parts/**",
                    "runs/{run_id}/actions/lemma_mine/scratch/**",
                    "runs/{run_id}/actions/lemma_mine/staging.yaml",
                ],
            ),
            _act(
                "lemma_verify",
                label_zh="引理候选对 R 反证",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                allowed_write_paths=[
                    "runs/{run_id}/actions/lemma_verify/verify.yaml",
                    "tg/closure/lemmas/verify.yaml",
                ],
            ),
            _act(
                "lemma_review",
                label_zh="引理资格审查",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="tg-closure-referee",
                role_id="referee",
                referee_required=True,
                execution_mode="subagent",
                capability_ids=["source-reading"],
                task_prompt_id="tg/lemma-review",
                output_contract_id="lemma-review-v1",
            ),
            _act(
                "lemma_apply",
                label_zh="应用已审引理到 E",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="lemma-apply-v1",
            ),
            _act(
                "lemma_loop",
                label_zh="引理可重入收敛",
                phases=["lemma"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="lemma-loop-v1",
                allowed_write_paths=[
                    "tg/closure/lemma_loop.yaml",
                    "tg/closure/rounds/**/lemma.yaml",
                    "runs/{run_id}/actions/lemma_mine/staging.yaml",
                    "runs/{run_id}/actions/lemma_review/review.yaml",
                    "tg/closure/excluded.txt",
                    "tg/closure/excluded_why.csv",
                    "tg/closure/open.txt",
                    "tg/closure/lemmas/active_rules.yaml",
                    "tg/closure/lemmas/reviews.yaml",
                ],
            ),
            _act(
                "closure_audit",
                label_zh="闭环不变量审查",
                phases=["audit"],
                workflow_id="tg-solve",
                agent_id="tg-closure-referee",
                role_id="referee",
                referee_required=True,
                execution_mode="subagent",
                capability_ids=["source-reading"],
                task_prompt_id="tg/closure-audit",
                output_contract_id="closure-audit-v1",
            ),
            _act(
                "closure_certify",
                label_zh="签发 gap=0 证书",
                phases=["certify"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["closure_soundness"],
                capability_ids=[],
                output_contract_id="closure-certify-v1",
            ),
            # csv_consumer 兼容
            _act(
                "z3_solve",
                label_zh="求解并投影",
                phases=["encode", "solve", "project"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="z3-solve-v1",
            ),
            _act(
                "cover_confirm",
                label_zh="覆盖确认",
                phases=["cover"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["solve_terminal"],
                capability_ids=[],
                output_contract_id="cover-confirm-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
            {"id": "tg-lemma-producer", "role": "producer"},
            {"id": "tg-closure-referee", "role": "referee"},
        ],
        "static_obligations": [
            {"id": "closure_soundness", "label_zh": "TilingKey 闭环健全"},
            {"id": "solve_terminal", "label_zh": "CSV 求解终态（csv_consumer）"},
        ],
        "dynamic_obligation_sources": ["tg/closure/**", "solve/**/uncovered_obligations.yaml"],
        "write_roots": ["tg", "runs", "state", "context"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": ["tg/solve", "tg/cases", "tg/closure"],
            "reinit_preserve": ["uo", "tg/init", "tg/plan", "tg/contract", "tg/extract"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": [
            "gate", "oracle", "ledger", "search", "residual",
            "construct", "lemma", "audit", "certify",
            "encode", "solve", "project", "cover",
        ],
        "gates": ["plan_approved", "closure_soundness", "solve_terminal", "kb_fingerprint_fresh"],
    },
    "code-edit": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "git-ops": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "build": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "test-run": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "perf-analyze": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
}
