"""TG workflow specs: init.yaml → plan.md → worklog.md + cases table.

Formal products are only those three (plus the cases table). Drafts stay
under runs/. Conflicting tilingkey_full_coverage / T=D / stamp overlays
do not exist here.
"""

from __future__ import annotations

from typing import Any, Callable


def attach_tg_workflows(
    workflows: dict[str, dict[str, Any]],
    *,
    _act: Callable[..., dict[str, Any]],
    _st: Callable[..., dict[str, str]],
    _tr: Callable[..., dict[str, Any]],
) -> None:
    workflows.update(_build(_act=_act, _st=_st, _tr=_tr))


def _build(
    *,
    _act: Callable[..., dict[str, Any]],
    _st: Callable[..., dict[str, str]],
    _tr: Callable[..., dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    return {
    "tg-init": {
        "slash": "/tg-init",
        "engine": "tg",
        "cognitive_skill_id": "testcase-generation",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "occupancy": "exclusive",
        "occupancy_group": "tg",
        "entry_state": "kb_ready",
        "terminal_ready_states": ["confirm"],
        "retry_budget": 3,
        "states": [
            _st("kb_ready", "校验知识库"),
            _st("scan", "扫描测试脚本仓"),
            _st("bind", "绑定列与 UO 标识符"),
            _st("validate", "校验 init.yaml"),
            _st("confirm", "确认进入规划"),
        ],
        "transitions": [
            _tr("kb_ready", "scan"),
            _tr("scan", "bind"),
            _tr("bind", "validate"),
            _tr("validate", "confirm"),
            _tr("validate", "bind", kind="rework", reason_codes=["INIT_INVALID", "MAPPING_EMPTY"]),
            _tr("confirm", "bind", kind="rework", reason_codes=["rework"]),
        ],
        "phase_gates": {
            "kb_ready": ["uo_ready"],
            "confirm": ["init_confirmed", "kb_fingerprint_fresh"],
        },
        "complete_gates": ["init_confirmed", "kb_fingerprint_fresh"],
        "pipelines": {
            "kb_ready": ["kb_check"],
            "scan": ["repo_scan"],
            "bind": ["bind_init", "bind_promote"],
            "validate": ["validate_init"],
            "confirm": ["human_confirm"],
        },
        "actions": [
            _act(
                "kb_check",
                label_zh="校验 CodeMap 就绪",
                phases=["kb_ready"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                pre_gates=["uo_ready"],
                capability_ids=[],
                output_contract_id="uo-ready-v1",
            ),
            _act(
                "repo_scan",
                label_zh="扫描测试脚本仓（含 xls/xlsx）",
                phases=["scan"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-repo-scan-v1",
                consumes_state=["test_script_root"],
            ),
            _act(
                "bind_init",
                label_zh="绑定列、值域、golden 与跑测口径",
                phases=["bind"],
                workflow_id="tg-init",
                agent_id="tg-analyst",
                role_id="producer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                action_method_id="testcase-generation/bind-init",
                task_prompt_id="tg/bind-init",
                context_profile_id="tg-init-bind-init",
                output_contract_id="tg-init-v1",
                output_mode="staged",
                staging_contract_id="tg-bind-staging-v1",
                merge_action_id="bind_promote",
            ),
            _act(
                "bind_promote",
                label_zh="写入 init.yaml",
                phases=["bind"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-init-v1",
            ),
            _act(
                "validate_init",
                label_zh="校验 mapping / 列 / 精度口径",
                phases=["validate"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-init-validate-v1",
            ),
            _act(
                "human_confirm",
                label_zh="确认进入规划",
                phases=["confirm"],
                workflow_id="tg-init",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                human_interaction="confirm",
                capability_ids=[],
                task_prompt_id=None,
                context_profile_id="tg-init-human-confirm",
                output_contract_id="tg-init-confirmed-v1",
                post_gates=["init_confirmed", "kb_fingerprint_fresh"],
            ),
        ],
        "agents": [
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
            {"id": "tg-analyst", "role": "producer"},
            {"id": "ascendc-pilot", "role": "controller"},
        ],
        "static_obligations": [
            {"id": "init_confirmed", "label_zh": "init.yaml 已确认"},
        ],
        "dynamic_obligation_sources": [],
        "write_roots": ["tg", "runs", "state", "context"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": ["tg/init.yaml", "tg/plan.md", "tg/worklog.md", "tg/cases.csv", "tg/cases.xls", "tg/cases.xlsx"],
            "reinit_preserve": ["uo"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["kb_ready", "scan", "bind", "validate", "confirm"],
        "gates": ["uo_ready", "init_confirmed", "kb_fingerprint_fresh"],
    },
    "tg-plan": {
        "slash": "/tg-plan",
        "engine": "tg",
        "cognitive_skill_id": "testcase-generation",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "occupancy": "exclusive",
        "occupancy_group": "tg",
        "entry_state": "gate",
        "terminal_ready_states": ["approve"],
        "retry_budget": 3,
        "states": [
            _st("gate", "校验 init.yaml"),
            _st("fuse", "融合意图写出义务"),
            _st("validate", "校验 YAML 义务表"),
            _st("approve", "批准规划"),
        ],
        "transitions": [
            _tr("gate", "fuse"),
            _tr("fuse", "validate"),
            _tr("validate", "approve"),
            _tr("validate", "fuse", kind="rework", reason_codes=["PLAN_INVALID"]),
            _tr("approve", "fuse", kind="rework", reason_codes=["rework"]),
        ],
        "phase_gates": {
            "gate": ["tg_init_confirmed", "kb_fingerprint_fresh"],
            "approve": ["plan_approved"],
        },
        "complete_gates": ["plan_approved"],
        "pipelines": {
            "gate": ["plan_precheck"],
            "fuse": ["plan_fuse", "plan_promote"],
            "validate": ["plan_validate"],
            "approve": ["plan_approve"],
        },
        "actions": [
            _act(
                "plan_precheck",
                label_zh="强制 init.yaml 并核对 UO digest",
                phases=["gate"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                pre_gates=["tg_init_confirmed", "kb_fingerprint_fresh"],
                capability_ids=[],
                output_contract_id="plan-precheck-v1",
            ),
            _act(
                "plan_fuse",
                label_zh="融合意图生成 plan.md",
                phases=["fuse"],
                workflow_id="tg-plan",
                agent_id="tg-analyst",
                role_id="producer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                action_method_id="testcase-generation/plan-fuse",
                task_prompt_id="tg/plan-fuse",
                context_profile_id="tg-plan-plan-fuse",
                output_contract_id="tg-plan-v1",
                output_mode="staged",
                staging_contract_id="tg-plan-staging-v1",
                merge_action_id="plan_promote",
            ),
            _act(
                "plan_promote",
                label_zh="写入 plan.md",
                phases=["fuse"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-plan-v1",
            ),
            _act(
                "plan_validate",
                label_zh="校验列 root / hit / budget",
                phases=["validate"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-plan-validate-v1",
            ),
            _act(
                "plan_approve",
                label_zh="批准规划",
                phases=["approve"],
                workflow_id="tg-plan",
                agent_id="ascendc-pilot",
                role_id="controller",
                execution_mode="primary_interactive",
                human_interaction="approve",
                capability_ids=[],
                task_prompt_id=None,
                context_profile_id="tg-plan-plan-approve",
                output_contract_id="tg-plan-approved-v1",
                post_gates=["plan_approved"],
            ),
        ],
        "agents": [
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
            {"id": "tg-analyst", "role": "producer"},
            {"id": "ascendc-pilot", "role": "controller"},
        ],
        "static_obligations": [
            {"id": "plan_approved", "label_zh": "plan.md 已批准"},
        ],
        "dynamic_obligation_sources": [],
        "write_roots": ["tg", "runs", "state", "context"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": ["tg/plan.md", "tg/worklog.md", "tg/cases.csv", "tg/cases.xls", "tg/cases.xlsx"],
            "reinit_preserve": ["uo", "tg/init.yaml"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["gate", "fuse", "validate", "approve"],
        "gates": ["tg_init_confirmed", "kb_fingerprint_fresh", "plan_approved"],
    },
    "tg-solve": {
        "slash": "/tg-solve",
        "engine": "tg",
        "cognitive_skill_id": "testcase-generation",
        "requires_project": True,
        "requires_architecture": False,
        "requires_uo_product": True,
        "occupancy": "exclusive",
        "occupancy_group": "tg",
        "entry_state": "gate",
        "terminal_ready_states": ["certify"],
        "retry_budget": 3,
        "states": [
            _st("gate", "校验已批准规划"),
            _st("construct", "构造用例表"),
            _st("replay", "Host 回放"),
            _st("analyze", "写 worklog"),
            _st("certify", "Open 为空则签发"),
        ],
        "transitions": [
            _tr("gate", "construct"),
            _tr("construct", "replay"),
            _tr("replay", "analyze"),
            _tr("analyze", "certify"),
            _tr("analyze", "construct", kind="rework", reason_codes=["REWORK_CONSTRUCT", "OPEN_REMAINING"]),
            _tr("certify", "construct", kind="rework", reason_codes=["OPEN_NONEMPTY"]),
        ],
        "phase_gates": {
            "gate": ["plan_approved", "kb_fingerprint_fresh", "test_harness_gap_cleared"],
            "certify": ["worklog_closed"],
        },
        "complete_gates": ["plan_approved", "worklog_closed"],
        "pipelines": {
            "gate": ["solve_precheck"],
            "construct": ["construct_cases", "construct_promote"],
            "replay": ["replay_round"],
            "analyze": ["analyze_round", "analyze_promote"],
            "certify": ["solve_certify"],
        },
        "actions": [
            _act(
                "solve_precheck",
                label_zh="禁止未落地 test_harness_gap 开求解",
                phases=["gate"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                pre_gates=["plan_approved", "kb_fingerprint_fresh", "test_harness_gap_cleared"],
                capability_ids=[],
                output_contract_id="solve-precheck-v1",
            ),
            _act(
                "construct_cases",
                label_zh="按义务构造用例行",
                phases=["construct"],
                workflow_id="tg-solve",
                agent_id="tg-analyst",
                role_id="producer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                action_method_id="testcase-generation/construct-cases",
                task_prompt_id="tg/construct-cases",
                context_profile_id="tg-solve-construct-cases",
                output_contract_id="tg-cases-v1",
                output_mode="staged",
                staging_contract_id="tg-construct-staging-v1",
                merge_action_id="construct_promote",
            ),
            _act(
                "construct_promote",
                label_zh="写出 cases.csv/xls",
                phases=["construct"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-cases-v1",
            ),
            _act(
                "replay_round",
                label_zh="Host tiling 回放（无 NPU）",
                phases=["replay"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-replay-v1",
            ),
            _act(
                "analyze_round",
                label_zh="按 case 写 worklog 四段",
                phases=["analyze"],
                workflow_id="tg-solve",
                agent_id="tg-analyst",
                role_id="producer",
                capability_ids=["kb-query", "source-navigation", "source-reading"],
                action_method_id="testcase-generation/analyze-round",
                task_prompt_id="tg/analyze-round",
                context_profile_id="tg-solve-analyze-round",
                output_contract_id="tg-worklog-v1",
                output_mode="staged",
                staging_contract_id="tg-analyze-staging-v1",
                merge_action_id="analyze_promote",
            ),
            _act(
                "analyze_promote",
                label_zh="写入 worklog.md",
                phases=["analyze"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-worklog-v1",
            ),
            _act(
                "solve_certify",
                label_zh="Open 为空则完成",
                phases=["certify"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                output_contract_id="tg-certify-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
            {"id": "tg-analyst", "role": "producer"},
            {"id": "ascendc-pilot", "role": "controller"},
        ],
        "static_obligations": [],
        "dynamic_obligation_sources": [],
        "write_roots": ["tg", "runs", "state", "context", "local"],
        "read_only_uo": True,
        "reset_policy": {
            "reinit_delete": ["tg/worklog.md", "tg/cases.csv", "tg/cases.xls", "tg/cases.xlsx"],
            "reinit_preserve": ["uo", "tg/init.yaml", "tg/plan.md"],
            "reinit_wipe_runs": "current",
            "continue_scrub": "from_contracts",
        },
        "phases": ["gate", "construct", "replay", "analyze", "certify"],
        "gates": ["plan_approved", "kb_fingerprint_fresh", "test_harness_gap_cleared", "worklog_closed"],
    },
}
