"""Concrete workflow specs (English ids + Chinese labels)."""

from __future__ import annotations

from typing import Any


def _st(sid: str, label_zh: str) -> dict[str, str]:
    return {"id": sid, "label_zh": label_zh}


def _tr(frm: str, to: str, *, kind: str = "forward", reason_codes: list[str] | None = None) -> dict[str, Any]:
    row: dict[str, Any] = {"from": frm, "to": to, "kind": kind}
    if reason_codes:
        row["reason_codes"] = reason_codes
    return row


def _act(
    action_id: str,
    *,
    label_zh: str,
    checker_required: bool = True,
    referee_required: bool = False,
    gates: list[str] | None = None,
    actors: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "id": action_id,
        "label_zh": label_zh,
        "checker_required": checker_required,
        "referee_required": referee_required,
        "gates": list(gates or []),
        "actors": list(actors or []),
    }


_UO_INIT_RESOLVE_GATES = [
    "key_triage_required",
    "key_resolve_receipt",
    "empty_only_producer",
    "confidence_gate",
    "key_report_quality",
    "confidence_closed_high",
    "confidence_reason_review",
]

WORKFLOWS: dict[str, dict[str, Any]] = {
    "uo-init": {
        "slash": "/uo-init",
        "engine": "uo",
        "entry_state": "prepare",
        "terminal_ready_states": ["review"],
        "retry_budget": 3,
        "states": [
            _st("prepare", "环境准备"),
            _st("scope", "范围确认"),
            _st("extract", "结构抽取"),
            _st("resolve", "语义闭合"),
            _st("export", "导出与校验"),
            _st("review", "产物审查"),
        ],
        "transitions": [
            _tr("prepare", "scope"),
            _tr("scope", "extract"),
            _tr("extract", "resolve"),
            _tr("resolve", "export"),
            _tr("export", "review"),
            _tr("extract", "scope", kind="rework", reason_codes=["SCOPE_REWORK", "PHASE0_FAILED"]),
            _tr("resolve", "extract", kind="rework", reason_codes=["EXTRACT_REWORK"]),
            _tr("resolve", "resolve", kind="rework", reason_codes=["KEY_REWORK", "CONFIDENCE_REWORK"]),
            _tr("export", "resolve", kind="rework", reason_codes=["INTEGRITY_REWORK"]),
            _tr("review", "resolve", kind="rework", reason_codes=["KB_REVIEW_REWORK", "input_derivable"]),
            _tr("review", "export", kind="rework", reason_codes=["export_graph"]),
            _tr("review", "scope", kind="rework", reason_codes=["phase0_scope"]),
        ],
        "phase_gates": {
            "prepare": [],
            "scope": ["phase0_receipt"],
            "extract": ["extract_plan_subagent"],
            "resolve": list(_UO_INIT_RESOLVE_GATES),
            "export": ["integrity"],
            "review": ["kb_review"],
        },
        "complete_gates": [
            *_UO_INIT_RESOLVE_GATES,
            "integrity",
            "kb_review",
        ],
        "actions": [
            _act("prepare_layout", label_zh="创建知识库目录"),
            _act("scope_confirmation", label_zh="确认分析范围", gates=["phase0_receipt"]),
            _act(
                "extract_plan",
                label_zh="抽取计划与分层 IR",
                gates=["extract_plan_subagent"],
                actors=["uo-semantic-resolve"],
            ),
            _act(
                "key_triage",
                label_zh="KEY 粗分",
                gates=["key_triage_required"],
                actors=["uo-key-resolve"],
            ),
            _act(
                "key_resolution",
                label_zh="KEY 语义闭合",
                gates=["key_resolve_receipt", "empty_only_producer"],
                actors=["uo-key-resolve"],
            ),
            _act(
                "confidence_report",
                label_zh="生成置信度报告",
                gates=["confidence_gate", "key_report_quality", "confidence_closed_high"],
                actors=["deterministic-uo-engine"],
            ),
            _act(
                "confidence_review",
                label_zh="置信度原因审查",
                referee_required=True,
                gates=["confidence_reason_review"],
                actors=["uo-confidence-review"],
            ),
            _act("export_integrity", label_zh="导出与完整性校验", gates=["integrity"]),
            _act(
                "kb_review",
                label_zh="KB 产物审查",
                referee_required=True,
                gates=["kb_review"],
                actors=["uo-kb-review"],
            ),
        ],
        "agents": [
            {"id": "uo-semantic-resolve", "role": "producer"},
            {"id": "uo-key-resolve", "role": "producer"},
            {"id": "uo-confidence-review", "role": "referee"},
            {"id": "uo-kb-review", "role": "referee"},
            {"id": "deterministic-uo-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [
            {"id": "scope_confirmed", "label_zh": "范围已确认"},
            {"id": "kb_integrity_passed", "label_zh": "完整性通过"},
            {"id": "kb_review_passed", "label_zh": "产物审查通过"},
        ],
        "dynamic_obligation_sources": ["ir/unresolved.yaml", "ir/input_derivable_gaps.yaml"],
        "write_roots": ["uo", "runs", "state", "context"],
        "phases": ["prepare", "scope", "extract", "resolve", "export", "review"],
        "gates": [
            "phase0_receipt",
            "extract_plan_subagent",
            *_UO_INIT_RESOLVE_GATES,
            "integrity",
            "kb_review",
        ],
    },
    "uo-update": {
        "slash": "/uo-update",
        "engine": "uo",
        "entry_state": "detect",
        "terminal_ready_states": ["diff"],
        "retry_budget": 3,
        "states": [
            _st("detect", "变更检测"),
            _st("plan", "更新计划"),
            _st("apply", "应用变更"),
            _st("resolve", "语义闭合"),
            _st("export", "导出与校验"),
            _st("diff", "差异摘要"),
        ],
        "transitions": [
            _tr("detect", "plan"),
            _tr("plan", "apply"),
            _tr("apply", "resolve"),
            _tr("resolve", "export"),
            _tr("export", "diff"),
            _tr("resolve", "resolve", kind="rework", reason_codes=["KEY_REWORK", "CONFIDENCE_REWORK"]),
            _tr("export", "resolve", kind="rework", reason_codes=["INTEGRITY_REWORK"]),
        ],
        "phase_gates": {
            "resolve": [
                "key_triage_required",
                "key_resolve_receipt",
                "confidence_gate",
                "confidence_reason_review",
            ],
            "export": ["integrity"],
        },
        "complete_gates": [
            "key_triage_required",
            "confidence_gate",
            "confidence_reason_review",
            "integrity",
        ],
        "actions": [
            _act("detect_changes", label_zh="检测源码变更"),
            _act("key_resolution", label_zh="KEY 语义闭合", actors=["uo-key-resolve"]),
            _act(
                "confidence_review",
                label_zh="置信度原因审查",
                referee_required=True,
                actors=["uo-confidence-review"],
            ),
            _act("diff_summary", label_zh="只读差异摘要", checker_required=False),
        ],
        "agents": [
            {"id": "uo-semantic-resolve", "role": "producer"},
            {"id": "uo-key-resolve", "role": "producer"},
            {"id": "uo-confidence-review", "role": "referee"},
            {"id": "uo-kb-review", "role": "referee"},
        ],
        "static_obligations": [{"id": "kb_integrity_passed", "label_zh": "完整性通过"}],
        "dynamic_obligation_sources": ["ir/unresolved.yaml", "ir/input_derivable_gaps.yaml"],
        "write_roots": ["uo", "runs", "state", "context"],
        "phases": ["detect", "plan", "apply", "resolve", "export", "diff"],
        "gates": [
            "key_triage_required",
            "key_resolve_receipt",
            "empty_only_producer",
            "confidence_gate",
            "confidence_reason_review",
            "integrity",
        ],
    },
    "uo-query": {
        "slash": "/uo-query",
        "engine": "uo",
        "entry_state": "route",
        "terminal_ready_states": ["answer"],
        "retry_budget": 3,
        "states": [
            _st("route", "问题路由"),
            _st("lookup", "知识检索"),
            _st("answer", "回答"),
        ],
        "transitions": [
            _tr("route", "lookup"),
            _tr("lookup", "answer"),
            _tr("lookup", "lookup", kind="rework", reason_codes=["LOOKUP_REWORK"]),
        ],
        "phase_gates": {"route": ["kb_ready"]},
        "complete_gates": ["kb_ready"],
        "actions": [_act("kb_lookup", label_zh="KB 查询", gates=["kb_ready"])],
        "agents": [{"id": "uo-key-resolve", "role": "producer"}],
        "static_obligations": [{"id": "kb_ready", "label_zh": "KB 就绪"}],
        "dynamic_obligation_sources": [],
        "write_roots": ["runs", "context", "memory"],
        "phases": ["route", "lookup", "answer"],
        "gates": ["kb_ready"],
    },
    "uo-code-review": {
        "slash": "/uo-code-review",
        "engine": "uo",
        "entry_state": "context",
        "terminal_ready_states": ["summary"],
        "retry_budget": 3,
        "states": [
            _st("context", "组装上下文"),
            _st("bug", "缺陷审查"),
            _st("functional", "功能审查"),
            _st("summary", "汇总"),
        ],
        "transitions": [
            _tr("context", "bug"),
            _tr("bug", "functional"),
            _tr("functional", "summary"),
        ],
        "phase_gates": {"context": ["kb_ready", "context_pack"]},
        "complete_gates": ["kb_ready", "context_pack"],
        "actions": [
            _act(
                "code_review",
                label_zh="代码审查",
                referee_required=True,
                actors=["uo-code-reviewer"],
            ),
        ],
        "agents": [{"id": "uo-code-reviewer", "role": "referee"}],
        "static_obligations": [{"id": "kb_ready", "label_zh": "KB 就绪"}],
        "dynamic_obligation_sources": [],
        "write_roots": ["uo/review", "runs", "context"],
        "phases": ["context", "bug", "functional", "summary"],
        "gates": ["kb_ready", "context_pack"],
    },
    "tg-init": {
        "slash": "/tg-init",
        "engine": "tg",
        "entry_state": "kb_ready",
        "terminal_ready_states": ["confirm"],
        "retry_budget": 3,
        "states": [
            _st("kb_ready", "KB 检查"),
            _st("contract", "合同构建"),
            _st("bind", "语义绑定"),
            _st("merge", "绑定合并"),
            _st("nest", "中间量闭合"),
            _st("gate", "完整性校验"),
            _st("confirm", "人工确认"),
        ],
        "transitions": [
            _tr("kb_ready", "contract"),
            _tr("contract", "bind"),
            _tr("bind", "merge"),
            _tr("merge", "nest"),
            _tr("nest", "gate"),
            _tr("gate", "confirm"),
            _tr("merge", "bind", kind="rework", reason_codes=["BIND_REWORK"]),
            _tr("gate", "merge", kind="rework", reason_codes=["MERGE_REWORK"]),
            _tr("confirm", "gate", kind="rework", reason_codes=["AUDIT_REWORK"]),
        ],
        "phase_gates": {
            "kb_ready": ["uo_ready", "kb_fingerprint_fresh"],
            "merge": ["merge_pass"],
            "gate": ["domain_symmetry", "csv_closure", "audit_pass"],
            "confirm": ["init_confirmed"],
        },
        "complete_gates": [
            "uo_ready",
            "kb_fingerprint_fresh",
            "merge_pass",
            "domain_symmetry",
            "csv_closure",
            "audit_pass",
            "init_confirmed",
        ],
        "actions": [
            _act("kb_check", label_zh="校验定稿 KB"),
            _act("contract_build", label_zh="构建合同骨架", actors=["tg-csv-contract"]),
            _act("semantic_bind", label_zh="语义绑定"),
            _act("bind_merge", label_zh="绑定合并", gates=["merge_pass"]),
            _act("mid_nest", label_zh="中间量闭合"),
            _act(
                "integrity_gate",
                label_zh="完整性校验",
                gates=["domain_symmetry", "csv_closure", "audit_pass"],
            ),
            _act(
                "human_confirm",
                label_zh="人工确认",
                referee_required=True,
                gates=["init_confirmed"],
                actors=["tg-init-audit"],
            ),
        ],
        "agents": [
            {"id": "tg-csv-contract", "role": "producer"},
            {"id": "tg-init-audit", "role": "referee"},
        ],
        "static_obligations": [
            {"id": "uo_ready", "label_zh": "UO KB 就绪"},
            {"id": "init_confirmed", "label_zh": "Init 已确认"},
        ],
        "dynamic_obligation_sources": [
            "realization/unresolved.yaml",
            "realization/binding_gaps.yaml",
        ],
        "write_roots": ["tg", "runs", "state", "context"],
        "read_only_uo": True,
        "phases": ["kb_ready", "contract", "bind", "merge", "nest", "gate", "confirm"],
        "gates": [
            "uo_ready",
            "kb_fingerprint_fresh",
            "merge_pass",
            "domain_symmetry",
            "csv_closure",
            "audit_pass",
            "init_confirmed",
        ],
    },
    "tg-plan": {
        "slash": "/tg-plan",
        "engine": "tg",
        "entry_state": "scope",
        "terminal_ready_states": ["approve"],
        "retry_budget": 3,
        "states": [
            _st("scope", "规划范围"),
            _st("gate", "前置门禁"),
            _st("build", "生成义务"),
            _st("filter", "过滤裁剪"),
            _st("review", "规划审查"),
            _st("approve", "人工批准"),
        ],
        "transitions": [
            _tr("scope", "gate"),
            _tr("gate", "build"),
            _tr("build", "filter"),
            _tr("filter", "review"),
            _tr("review", "approve"),
            _tr("approve", "review", kind="rework", reason_codes=["PLAN_REWORK"]),
        ],
        "phase_gates": {
            "gate": ["tg_init_confirmed", "kb_fingerprint_fresh"],
            "approve": ["plan_approved"],
        },
        "complete_gates": ["tg_init_confirmed", "plan_approved"],
        "actions": [
            _act("plan_build", label_zh="生成覆盖义务"),
            _act("plan_approve", label_zh="批准规划", gates=["plan_approved"]),
        ],
        "agents": [],
        "static_obligations": [{"id": "plan_approved", "label_zh": "规划已批准"}],
        "dynamic_obligation_sources": ["plan/**/uncovered_obligations.yaml"],
        "write_roots": ["tg", "runs", "state"],
        "read_only_uo": True,
        "phases": ["scope", "gate", "build", "filter", "review", "approve"],
        "gates": ["tg_init_confirmed", "plan_approved"],
    },
    "tg-solve": {
        "slash": "/tg-solve",
        "engine": "tg",
        "entry_state": "gate",
        "terminal_ready_states": ["cover"],
        "retry_budget": 3,
        "states": [
            _st("gate", "求解前置"),
            _st("encode", "编码约束"),
            _st("solve", "Z3 求解"),
            _st("project", "CSV 投影"),
            _st("cover", "覆盖确认"),
        ],
        "transitions": [
            _tr("gate", "encode"),
            _tr("encode", "solve"),
            _tr("solve", "project"),
            _tr("project", "cover"),
            _tr("solve", "encode", kind="rework", reason_codes=["SOLVE_REWORK"]),
        ],
        "phase_gates": {
            "gate": ["plan_approved", "kb_fingerprint_fresh"],
            "cover": ["solve_terminal"],
        },
        "complete_gates": ["plan_approved", "solve_terminal"],
        "actions": [
            _act("z3_solve", label_zh="求解并投影", gates=["solve_terminal"]),
        ],
        "agents": [],
        "static_obligations": [{"id": "solve_terminal", "label_zh": "求解终态完成"}],
        "dynamic_obligation_sources": ["solve/**/uncovered_obligations.yaml"],
        "write_roots": ["tg", "runs", "state"],
        "read_only_uo": True,
        "phases": ["gate", "encode", "solve", "project", "cover"],
        "gates": ["plan_approved", "solve_terminal"],
    },
    "code-edit": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "git-ops": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "build": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "test-run": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "perf-analyze": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
}
