"""Concrete workflow specs (English ids + Chinese labels)."""

from __future__ import annotations

from typing import Any

# Shared stable policies composed into every semantic / engine action.
DEFAULT_POLICY_IDS: list[str] = [
    "source-authority",
    "code-access",
    "evidence",
    "language",
    "harness-control",
    "output-quality",
]


def _st(sid: str, label_zh: str) -> dict[str, str]:
    return {"id": sid, "label_zh": label_zh}


def _tr(frm: str, to: str, *, kind: str = "forward", reason_codes: list[str] | None = None) -> dict[str, Any]:
    row: dict[str, Any] = {"from": frm, "to": to, "kind": kind}
    if reason_codes:
        row["reason_codes"] = reason_codes
    return row


def _act(
    action_id: str,
    *,
    label_zh: str,
    phases: list[str],
    workflow_id: str,
    checker_required: bool = True,
    referee_required: bool = False,
    gates: list[str] | None = None,
    agent_id: str | None = None,
    role_id: str | None = None,
    policy_ids: list[str] | None = None,
    capability_ids: list[str] | None = None,
    action_method_id: str | None = None,
    task_prompt_id: str | None = None,
    context_profile_id: str | None = None,
    output_contract_id: str | None = None,
) -> dict[str, Any]:
    """Declare a Harness Action with compositional references.

    ``actors`` is derived from ``agent_id`` for authorize / spawn checks.
    """
    method_id = action_method_id or f"{workflow_id}/{action_id.replace('_', '-')}"
    actors = [agent_id] if agent_id else []
    return {
        "id": action_id,
        "label_zh": label_zh,
        "phases": list(phases),
        "checker_required": checker_required,
        "referee_required": referee_required,
        "gates": list(gates or []),
        "agent_id": agent_id,
        "role_id": role_id,
        "policy_ids": list(policy_ids if policy_ids is not None else DEFAULT_POLICY_IDS),
        "capability_ids": list(capability_ids or []),
        "action_method_id": method_id,
        "task_prompt_id": task_prompt_id,
        "context_profile_id": context_profile_id or f"{workflow_id}-{action_id.replace('_', '-')}",
        "output_contract_id": output_contract_id,
        # Derived for authorize / Task spawn (single primary actor).
        "actors": actors,
    }


_UO_INIT_RESOLVE_GATES = [
    "key_triage_required",
    "key_resolve_receipt",
    "empty_only_producer",
    "confidence_gate",
    "key_report_quality",
    "confidence_closed_high",
    "confidence_reason_review",
]

# Static obligation id → gate id that settles it when that gate passes.
STATIC_OBLIGATION_GATE_MAP: dict[str, str] = {
    "scope_confirmed": "scope_receipt",
    "kb_integrity_passed": "integrity",
    "kb_review_passed": "kb_review",
    "kb_ready": "kb_ready",
    "uo_ready": "uo_ready",
    "init_confirmed": "init_confirmed",
    "plan_approved": "plan_approved",
    "solve_terminal": "solve_terminal",
}

CLOSED_OBLIGATION_STATUSES = frozenset(
    {
        "resolved",
        "verified",
        "not_applicable",
        "human_required",
        "blocked",
        "rejected",
    }
)

_CAPS_CODE = ["source-reading", "cbm-navigation", "kb-query"]
_CAPS_RESOLVE = ["source-reading", "cbm-navigation", "kb-query", "semantic-resolution"]
_CAPS_REVIEW = ["structured-review", "kb-query"]
_CAPS_CONTRACT = ["contract-building", "kb-query", "obligation-analysis"]
_CAPS_OBLIGATION = ["obligation-analysis", "kb-query"]

WORKFLOWS: dict[str, dict[str, Any]] = {
    "uo-init": {
        "slash": "/uo-init",
        "engine": "uo",
        "entry_state": "prepare",
        "terminal_ready_states": ["review"],
        "retry_budget": 3,
        "states": [
            _st("prepare", "环境准备"),
            _st("scope", "范围确认"),
            _st("extract", "结构抽取"),
            _st("resolve", "语义闭合"),
            _st("export", "导出与校验"),
            _st("review", "产物审查"),
        ],
        "transitions": [
            _tr("prepare", "scope"),
            _tr("scope", "extract"),
            _tr("extract", "resolve"),
            _tr("resolve", "export"),
            _tr("export", "review"),
            _tr("extract", "scope", kind="rework", reason_codes=["SCOPE_REWORK", "SCOPE_FAILED"]),
            _tr("resolve", "extract", kind="rework", reason_codes=["EXTRACT_REWORK"]),
            _tr("resolve", "resolve", kind="rework", reason_codes=["KEY_REWORK", "CONFIDENCE_REWORK"]),
            _tr("export", "resolve", kind="rework", reason_codes=["INTEGRITY_REWORK"]),
            _tr("review", "resolve", kind="rework", reason_codes=["KB_REVIEW_REWORK", "input_derivable"]),
            _tr("review", "export", kind="rework", reason_codes=["export_graph"]),
            _tr("review", "scope", kind="rework", reason_codes=["scope", "SCOPE_REWORK"]),
        ],
        "phase_gates": {
            "prepare": [],
            "scope": ["scope_receipt"],
            "extract": ["detect_score_pre", "extract_plan_subagent", "semantic_closure", "detect_score_post"],
            "resolve": list(_UO_INIT_RESOLVE_GATES),
            "export": ["integrity"],
            "review": ["kb_review"],
        },
        "complete_gates": [
            *_UO_INIT_RESOLVE_GATES,
            "integrity",
            "kb_review",
        ],
        "meta": {
            "max_semantic_resolve_attempts": 3,
            "max_semantic_batches": 8,
        },
        "actions": [
            _act(
                "prepare_layout",
                label_zh="创建知识库目录",
                phases=["prepare"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="kb-layout-v1",
            ),
            _act(
                "scope_confirmation",
                label_zh="确认分析范围",
                phases=["scope"],
                workflow_id="uo-init",
                agent_id="ascendc-agent",
                role_id="producer",
                gates=["scope_receipt"],
                capability_ids=["cbm-navigation", "source-reading"],
                task_prompt_id="uo/scope-confirmation",
                output_contract_id="scope-confirmed-v1",
            ),
            _act(
                "detect_score_pre",
                label_zh="抽取前评分(pre_semantic)",
                phases=["extract"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["detect_score_pre"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="detect-score-pre-v1",
            ),
            _act(
                "extract_plan",
                label_zh="抽取计划与分层 IR",
                phases=["extract"],
                workflow_id="uo-init",
                agent_id="uo-semantic-resolve",
                role_id="producer",
                gates=["extract_plan_subagent"],
                capability_ids=_CAPS_CODE + ["semantic-resolution"],
                task_prompt_id="uo/extract-plan",
                output_contract_id="extract-plan-v1",
            ),
            _act(
                "apply_semantic_patch",
                label_zh="应用语义补丁(ledger)",
                phases=["extract", "resolve"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=[],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="semantic-patch-v1",
            ),
            _act(
                "rebuild_from_ledger",
                label_zh="由账本重建派生图",
                phases=["extract", "resolve"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=[],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="rebuild-ledger-v1",
            ),
            _act(
                "detect_score_post",
                label_zh="抽取后评分(post_semantic)",
                phases=["extract"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["detect_score_post"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="detect-score-post-v1",
            ),
            _act(
                "recheck_closure",
                label_zh="复核闭合(不增 attempts)",
                phases=["extract", "resolve"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["semantic_closure"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="recheck-closure-v1",
            ),
            _act(
                "key_triage",
                label_zh="KEY 粗分",
                phases=["resolve"],
                workflow_id="uo-init",
                agent_id="uo-key-resolve",
                role_id="producer",
                gates=["key_triage_required"],
                capability_ids=_CAPS_RESOLVE,
                task_prompt_id="uo/key-triage",
                output_contract_id="key-triage-v1",
            ),
            _act(
                "key_resolution",
                label_zh="KEY 语义闭合",
                phases=["resolve"],
                workflow_id="uo-init",
                agent_id="uo-key-resolve",
                role_id="producer",
                gates=["key_resolve_receipt", "empty_only_producer"],
                capability_ids=_CAPS_RESOLVE,
                task_prompt_id="uo/key-resolution",
                output_contract_id="input-derivable-patch-v1",
            ),
            _act(
                "confidence_report",
                label_zh="生成置信度报告",
                phases=["resolve"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["confidence_gate", "key_report_quality", "confidence_closed_high"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="confidence-report-v1",
            ),
            _act(
                "confidence_review",
                label_zh="置信度原因审查",
                phases=["resolve"],
                workflow_id="uo-init",
                agent_id="uo-confidence-review",
                role_id="referee",
                referee_required=True,
                gates=["confidence_reason_review"],
                capability_ids=_CAPS_REVIEW,
                task_prompt_id="uo/confidence-review",
                output_contract_id="confidence-reason-review-v1",
            ),
            _act(
                "export_integrity",
                label_zh="导出与完整性校验",
                phases=["export"],
                workflow_id="uo-init",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["integrity"],
                capability_ids=[],
                task_prompt_id=None,
                output_contract_id="integrity-v1",
            ),
            _act(
                "kb_review",
                label_zh="KB 产物审查",
                phases=["review"],
                workflow_id="uo-init",
                agent_id="uo-kb-review",
                role_id="referee",
                referee_required=True,
                gates=["kb_review"],
                capability_ids=_CAPS_REVIEW,
                task_prompt_id="uo/kb-review",
                output_contract_id="kb-review-v1",
            ),
        ],
        "agents": [
            {"id": "uo-semantic-resolve", "role": "producer"},
            {"id": "uo-key-resolve", "role": "producer"},
            {"id": "uo-confidence-review", "role": "referee"},
            {"id": "uo-kb-review", "role": "referee"},
            {"id": "deterministic-uo-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [
            {"id": "scope_confirmed", "label_zh": "范围已确认"},
            {"id": "kb_integrity_passed", "label_zh": "完整性通过"},
            {"id": "kb_review_passed", "label_zh": "产物审查通过"},
        ],
        "dynamic_obligation_sources": ["ir/unresolved.yaml", "ir/input_derivable_gaps.yaml"],
        "write_roots": ["uo", "runs", "state", "context"],
        "phases": ["prepare", "scope", "extract", "resolve", "export", "review"],
        "gates": [
            "scope_receipt",
            "extract_plan_subagent",
            *_UO_INIT_RESOLVE_GATES,
            "integrity",
            "kb_review",
        ],
    },
    "uo-update": {
        "slash": "/uo-update",
        "engine": "uo",
        "entry_state": "detect",
        "terminal_ready_states": ["diff"],
        "retry_budget": 3,
        "states": [
            _st("detect", "变更检测"),
            _st("plan", "更新计划"),
            _st("apply", "应用变更"),
            _st("resolve", "语义闭合"),
            _st("export", "导出与校验"),
            _st("diff", "差异摘要"),
        ],
        "transitions": [
            _tr("detect", "plan"),
            _tr("plan", "apply"),
            _tr("apply", "resolve"),
            _tr("resolve", "export"),
            _tr("export", "diff"),
            _tr("resolve", "resolve", kind="rework", reason_codes=["KEY_REWORK", "CONFIDENCE_REWORK"]),
            _tr("export", "resolve", kind="rework", reason_codes=["INTEGRITY_REWORK"]),
            _tr("detect", "diff", kind="forward", reason_codes=["DIFF_ONLY"]),
        ],
        "phase_gates": {
            "resolve": [
                "key_triage_required",
                "key_resolve_receipt",
                "empty_only_producer",
                "confidence_gate",
                "confidence_reason_review",
            ],
            "export": ["integrity"],
        },
        "complete_gates": [
            "key_triage_required",
            "empty_only_producer",
            "confidence_gate",
            "confidence_reason_review",
            "integrity",
        ],
        "complete_gates_diff_only": [],
        "actions": [
            _act(
                "detect_changes",
                label_zh="检测源码变更",
                phases=["detect"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=["source-reading"],
                output_contract_id="change-detect-v1",
            ),
            _act(
                "plan_update",
                label_zh="制定更新计划",
                phases=["plan"],
                workflow_id="uo-update",
                agent_id="uo-semantic-resolve",
                role_id="producer",
                capability_ids=_CAPS_CODE + ["semantic-resolution"],
                task_prompt_id="uo/plan-update",
                output_contract_id="update-plan-v1",
            ),
            _act(
                "apply_update",
                label_zh="应用变更",
                phases=["apply"],
                workflow_id="uo-update",
                agent_id="uo-semantic-resolve",
                role_id="producer",
                capability_ids=_CAPS_RESOLVE,
                task_prompt_id="uo/apply-update",
                output_contract_id="update-apply-v1",
            ),
            _act(
                "key_resolution",
                label_zh="KEY 语义闭合",
                phases=["resolve"],
                workflow_id="uo-update",
                agent_id="uo-key-resolve",
                role_id="producer",
                gates=["key_triage_required", "key_resolve_receipt"],
                capability_ids=_CAPS_RESOLVE,
                task_prompt_id="uo/key-resolution",
                output_contract_id="input-derivable-patch-v1",
            ),
            _act(
                "confidence_report",
                label_zh="生成置信度报告",
                phases=["resolve"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["confidence_gate"],
                capability_ids=[],
                output_contract_id="confidence-report-v1",
            ),
            _act(
                "confidence_review",
                label_zh="置信度原因审查",
                phases=["resolve"],
                workflow_id="uo-update",
                agent_id="uo-confidence-review",
                role_id="referee",
                referee_required=True,
                gates=["confidence_reason_review"],
                capability_ids=_CAPS_REVIEW,
                task_prompt_id="uo/confidence-review",
                output_contract_id="confidence-reason-review-v1",
            ),
            _act(
                "export_integrity",
                label_zh="导出与完整性校验",
                phases=["export"],
                workflow_id="uo-update",
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                gates=["integrity"],
                capability_ids=[],
                output_contract_id="integrity-v1",
            ),
            _act(
                "diff_summary",
                label_zh="只读差异摘要",
                phases=["diff", "detect"],
                workflow_id="uo-update",
                checker_required=False,
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=["kb-query"],
                output_contract_id="diff-summary-v1",
            ),
            _act(
                "diff_only",
                label_zh="仅差异摘要（跳过完整更新）",
                phases=["detect", "diff"],
                workflow_id="uo-update",
                checker_required=False,
                agent_id="deterministic-uo-engine",
                role_id="deterministic_engine",
                capability_ids=["kb-query"],
                output_contract_id="diff-summary-v1",
            ),
        ],
        "agents": [
            {"id": "uo-semantic-resolve", "role": "producer"},
            {"id": "uo-key-resolve", "role": "producer"},
            {"id": "uo-confidence-review", "role": "referee"},
            {"id": "uo-kb-review", "role": "referee"},
            {"id": "deterministic-uo-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [{"id": "kb_integrity_passed", "label_zh": "完整性通过"}],
        "dynamic_obligation_sources": ["ir/unresolved.yaml", "ir/input_derivable_gaps.yaml"],
        "write_roots": ["uo", "runs", "state", "context"],
        "phases": ["detect", "plan", "apply", "resolve", "export", "diff"],
        "gates": [
            "key_triage_required",
            "key_resolve_receipt",
            "empty_only_producer",
            "confidence_gate",
            "confidence_reason_review",
            "integrity",
        ],
    },
    "uo-query": {
        "slash": "/uo-query",
        "engine": "uo",
        "entry_state": "route",
        "terminal_ready_states": ["answer"],
        "retry_budget": 3,
        "states": [
            _st("route", "问题路由"),
            _st("lookup", "知识检索"),
            _st("answer", "回答"),
        ],
        "transitions": [
            _tr("route", "lookup"),
            _tr("lookup", "answer"),
            _tr("lookup", "lookup", kind="rework", reason_codes=["LOOKUP_REWORK"]),
        ],
        "phase_gates": {"route": ["kb_ready"]},
        "complete_gates": ["kb_ready"],
        "actions": [
            _act(
                "kb_lookup",
                label_zh="KB 查询",
                phases=["route", "lookup", "answer"],
                workflow_id="uo-query",
                agent_id="uo-query",
                role_id="readonly_analyst",
                gates=["kb_ready"],
                capability_ids=["kb-query", "cbm-navigation", "source-reading"],
                task_prompt_id="uo/kb-lookup",
                output_contract_id="kb-answer-v1",
            ),
        ],
        "agents": [{"id": "uo-query", "role": "readonly_analyst"}],
        "static_obligations": [{"id": "kb_ready", "label_zh": "KB 就绪"}],
        "dynamic_obligation_sources": [],
        "write_roots": ["runs", "context", "memory"],
        "phases": ["route", "lookup", "answer"],
        "gates": ["kb_ready"],
    },
    "uo-code-review": {
        "slash": "/uo-code-review",
        "engine": "uo",
        "entry_state": "context",
        "terminal_ready_states": ["summary"],
        "retry_budget": 3,
        "states": [
            _st("context", "组装上下文"),
            _st("bug", "缺陷审查"),
            _st("functional", "功能审查"),
            _st("summary", "汇总"),
        ],
        "transitions": [
            _tr("context", "bug"),
            _tr("bug", "functional"),
            _tr("functional", "summary"),
        ],
        "phase_gates": {"context": ["kb_ready", "context_pack"]},
        "complete_gates": ["kb_ready", "context_pack"],
        "actions": [
            _act(
                "code_review",
                label_zh="代码审查",
                phases=["context", "bug", "functional", "summary"],
                workflow_id="uo-code-review",
                agent_id="uo-code-reviewer",
                role_id="readonly_analyst",
                capability_ids=["structured-review", "kb-query", "cbm-navigation", "source-reading"],
                task_prompt_id="uo/code-review",
                output_contract_id="code-review-v1",
            ),
        ],
        "agents": [{"id": "uo-code-reviewer", "role": "readonly_analyst"}],
        "static_obligations": [{"id": "kb_ready", "label_zh": "KB 就绪"}],
        "dynamic_obligation_sources": [],
        "write_roots": ["uo/review", "runs", "context"],
        "phases": ["context", "bug", "functional", "summary"],
        "gates": ["kb_ready", "context_pack"],
    },
    "tg-init": {
        "slash": "/tg-init",
        "engine": "tg",
        "entry_state": "kb_ready",
        "terminal_ready_states": ["confirm"],
        "retry_budget": 3,
        "states": [
            _st("kb_ready", "KB 检查"),
            _st("contract", "合同构建"),
            _st("bind", "语义绑定"),
            _st("merge", "绑定合并"),
            _st("nest", "中间量闭合"),
            _st("gate", "完整性校验"),
            _st("confirm", "人工确认"),
        ],
        "transitions": [
            _tr("kb_ready", "contract"),
            _tr("contract", "bind"),
            _tr("bind", "merge"),
            _tr("merge", "nest"),
            _tr("nest", "gate"),
            _tr("gate", "confirm"),
            _tr("merge", "bind", kind="rework", reason_codes=["BIND_REWORK"]),
            _tr("gate", "merge", kind="rework", reason_codes=["MERGE_REWORK"]),
            _tr("confirm", "gate", kind="rework", reason_codes=["AUDIT_REWORK"]),
        ],
        "phase_gates": {
            "kb_ready": ["uo_ready"],
            "merge": ["merge_pass"],
            "gate": ["domain_symmetry", "csv_closure", "audit_pass"],
            "confirm": ["init_confirmed", "kb_fingerprint_fresh"],
        },
        "complete_gates": [
            "uo_ready",
            "merge_pass",
            "domain_symmetry",
            "csv_closure",
            "audit_pass",
            "init_confirmed",
            "kb_fingerprint_fresh",
        ],
        "actions": [
            _act(
                "kb_check",
                label_zh="校验定稿 KB",
                phases=["kb_ready"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["uo_ready"],
                capability_ids=["kb-query"],
                output_contract_id="uo-ready-v1",
            ),
            _act(
                "contract_build",
                label_zh="构建合同骨架",
                phases=["contract"],
                workflow_id="tg-init",
                agent_id="tg-csv-contract",
                role_id="producer",
                capability_ids=_CAPS_CONTRACT,
                task_prompt_id="tg/contract-build",
                output_contract_id="csv-contract-v1",
            ),
            _act(
                "semantic_bind",
                label_zh="语义绑定",
                phases=["bind"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=["kb-query", "semantic-resolution"],
                output_contract_id="semantic-bind-v1",
            ),
            _act(
                "bind_merge",
                label_zh="绑定合并",
                phases=["merge"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["merge_pass"],
                capability_ids=[],
                output_contract_id="bind-merge-v1",
            ),
            _act(
                "mid_nest",
                label_zh="中间量闭合",
                phases=["nest"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=["obligation-analysis"],
                output_contract_id="mid-nest-v1",
            ),
            _act(
                "integrity_gate",
                label_zh="完整性校验",
                phases=["gate"],
                workflow_id="tg-init",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["domain_symmetry", "csv_closure"],
                capability_ids=[],
                output_contract_id="tg-integrity-v1",
            ),
            _act(
                "init_audit",
                label_zh="Init 审计",
                phases=["gate"],
                workflow_id="tg-init",
                agent_id="tg-init-audit",
                role_id="referee",
                referee_required=True,
                gates=["audit_pass"],
                capability_ids=_CAPS_REVIEW,
                task_prompt_id="tg/init-audit",
                output_contract_id="init-audit-v1",
            ),
            _act(
                "human_confirm",
                label_zh="人工确认",
                phases=["confirm"],
                workflow_id="tg-init",
                agent_id=None,
                role_id=None,
                gates=["init_confirmed", "kb_fingerprint_fresh"],
                capability_ids=[],
                task_prompt_id="tg/human-confirm",
                output_contract_id="init-confirmed-v1",
            ),
        ],
        "agents": [
            {"id": "tg-csv-contract", "role": "producer"},
            {"id": "tg-init-audit", "role": "referee"},
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [
            {"id": "uo_ready", "label_zh": "UO KB 就绪"},
            {"id": "init_confirmed", "label_zh": "Init 已确认"},
        ],
        "dynamic_obligation_sources": [
            "realization/unresolved.yaml",
            "realization/binding_gaps.yaml",
        ],
        "write_roots": ["tg", "runs", "state", "context"],
        "read_only_uo": True,
        "phases": ["kb_ready", "contract", "bind", "merge", "nest", "gate", "confirm"],
        "gates": [
            "uo_ready",
            "kb_fingerprint_fresh",
            "merge_pass",
            "domain_symmetry",
            "csv_closure",
            "audit_pass",
            "init_confirmed",
        ],
    },
    "tg-plan": {
        "slash": "/tg-plan",
        "engine": "tg",
        "entry_state": "scope",
        "terminal_ready_states": ["approve"],
        "retry_budget": 3,
        "states": [
            _st("scope", "规划范围"),
            _st("gate", "前置门禁"),
            _st("build", "生成义务"),
            _st("filter", "过滤裁剪"),
            _st("review", "规划审查"),
            _st("approve", "人工批准"),
        ],
        "transitions": [
            _tr("scope", "gate"),
            _tr("gate", "build"),
            _tr("build", "filter"),
            _tr("filter", "review"),
            _tr("review", "approve"),
            _tr("approve", "review", kind="rework", reason_codes=["PLAN_REWORK"]),
        ],
        "phase_gates": {
            "gate": ["tg_init_confirmed", "kb_fingerprint_fresh"],
            "approve": ["plan_approved"],
        },
        "complete_gates": ["tg_init_confirmed", "plan_approved"],
        "actions": [
            _act(
                "plan_scope",
                label_zh="确定规划范围",
                phases=["scope"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=_CAPS_OBLIGATION,
                output_contract_id="plan-scope-v1",
            ),
            _act(
                "plan_precheck",
                label_zh="规划前置门禁",
                phases=["gate"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["tg_init_confirmed", "kb_fingerprint_fresh"],
                capability_ids=[],
                output_contract_id="plan-precheck-v1",
            ),
            _act(
                "plan_build",
                label_zh="生成覆盖义务",
                phases=["build", "filter", "review"],
                workflow_id="tg-plan",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=_CAPS_OBLIGATION,
                output_contract_id="plan-build-v1",
            ),
            _act(
                "plan_approve",
                label_zh="批准规划",
                phases=["approve"],
                workflow_id="tg-plan",
                agent_id=None,
                role_id=None,
                gates=["plan_approved"],
                capability_ids=[],
                task_prompt_id="tg/plan-approve",
                output_contract_id="plan-approved-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [{"id": "plan_approved", "label_zh": "规划已批准"}],
        "dynamic_obligation_sources": ["plan/**/uncovered_obligations.yaml"],
        "write_roots": ["tg", "runs", "state"],
        "read_only_uo": True,
        "phases": ["scope", "gate", "build", "filter", "review", "approve"],
        "gates": ["tg_init_confirmed", "plan_approved"],
    },
    "tg-solve": {
        "slash": "/tg-solve",
        "engine": "tg",
        "entry_state": "gate",
        "terminal_ready_states": ["cover"],
        "retry_budget": 3,
        "states": [
            _st("gate", "求解前置"),
            _st("encode", "编码约束"),
            _st("solve", "Z3 求解"),
            _st("project", "CSV 投影"),
            _st("cover", "覆盖确认"),
        ],
        "transitions": [
            _tr("gate", "encode"),
            _tr("encode", "solve"),
            _tr("solve", "project"),
            _tr("project", "cover"),
            _tr("solve", "encode", kind="rework", reason_codes=["SOLVE_REWORK"]),
        ],
        "phase_gates": {
            "gate": ["plan_approved", "kb_fingerprint_fresh"],
            "cover": ["solve_terminal"],
        },
        "complete_gates": ["plan_approved", "solve_terminal", "domain_symmetry"],
        "actions": [
            _act(
                "solve_precheck",
                label_zh="求解前置校验",
                phases=["gate"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["plan_approved", "kb_fingerprint_fresh"],
                capability_ids=[],
                output_contract_id="solve-precheck-v1",
            ),
            _act(
                "z3_solve",
                label_zh="求解并投影",
                phases=["encode", "solve", "project"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                capability_ids=["obligation-analysis"],
                output_contract_id="z3-solve-v1",
            ),
            _act(
                "cover_confirm",
                label_zh="覆盖确认",
                phases=["cover"],
                workflow_id="tg-solve",
                agent_id="deterministic-tg-engine",
                role_id="deterministic_engine",
                gates=["solve_terminal"],
                capability_ids=["obligation-analysis"],
                output_contract_id="cover-confirm-v1",
            ),
        ],
        "agents": [
            {"id": "deterministic-tg-engine", "role": "deterministic_engine"},
        ],
        "static_obligations": [{"id": "solve_terminal", "label_zh": "求解终态完成"}],
        "dynamic_obligation_sources": ["solve/**/uncovered_obligations.yaml"],
        "write_roots": ["tg", "runs", "state"],
        "read_only_uo": True,
        "phases": ["gate", "encode", "solve", "project", "cover"],
        "gates": ["plan_approved", "solve_terminal", "domain_symmetry"],
    },
    "code-edit": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "git-ops": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "build": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "test-run": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
    "perf-analyze": {"slash": None, "engine": "ext", "phases": [], "gates": [], "states": [], "reserved": True},
}
