ASCENDC_TPL_ARGS_DECL(Toy,
  ASCENDC_TPL_BOOL_DECL(TPL_ISPERBLOCK, 0, 1),
  ASCENDC_TPL_UINT_DECL(TPL_INPUT, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, 0, 1),
  ASCENDC_TPL_UINT_DECL(TPL_OUTPUT, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, 0, 1),
  ASCENDC_TPL_UINT_DECL(TPL_COMM, ASCENDC_TPL_1_BW, ASCENDC_TPL_UI_LIST, 0, 1));
