#define SET_HELPER(tag) ASCENDC_TPL_BOOL_SEL(FLAG, 0), ASCENDC_TPL_UINT_SEL(MODE, ASCENDC_TPL_UI_LIST, MODE_##tag)
ASCENDC_TPL_ARGS_DECL(Toy,
  ASCENDC_TPL_BOOL_DECL(FLAG, 0, 1),
  ASCENDC_TPL_UINT_DECL(MODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MODE_A, MODE_B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(A));
ASCENDC_TPL_ARGS_SEL(SET_HELPER(B));
