# -*- coding: utf-8 -*-
"""Grade each extracted premise against every case the host already judged.

Two numbers matter per premise and they are not symmetric. Catching a refusal
early saves a round trip through WSL. Refusing a case the host accepted
destroys a witness, and no saving justifies it.

A premise that refuses a real witness is not wrong about what it says -- it is
missing the condition under which the host asks it. `CheckSoftmaxMaxShape`
requires rank 4, and TND never calls it: the extraction kept the check and
dropped its call-site guard. Until the guard is recovered such a premise
cannot gate anything, so this writes a grade per premise and the preflight
consults only the ones that have never cost a witness.
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from replay import bridge as B  # noqa: E402
from replay import runner as R  # noqa: E402
from replay_derivation_check import case_of  # noqa: E402

GRADES = R.CACHE / "premise_grades.yaml"


def main() -> int:
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    prem = B.premises()
    caught: Counter = Counter()
    false: Counter = Counter()
    victim: dict[int, str] = {}
    rows = accepted = refused = blocked = 0

    for path in sorted(R.CACHE.glob("fag_key_cases*.csv")):
        lines = path.read_text(encoding="utf-8").splitlines()
        head = lines[0].split(",")
        for line in lines[1:]:
            f = line.split(",")
            if len(f) != len(head):
                continue
            row = dict(zip(head, f))
            rows += 1
            if limit and rows > limit:
                break
            host_ok = row.get("ok") == "1"
            env = B.env_of(case_of(row))
            hit = [i for i, (t, _) in enumerate(prem.sourced)
                   if _refuses(t, env)]
            if host_ok:
                accepted += 1
                for i in hit:
                    false[i] += 1
                    victim.setdefault(i, f"{row['case_id']} layout={row.get('layout')}")
            else:
                refused += 1
                if hit:
                    blocked += 1
                for i in hit:
                    caught[i] += 1
        if limit and rows > limit:
            break

    lines_out = ["# Generated by replay_preflight_calibrate.py. Do not hand-edit.",
                 f"corpus_cases: {rows}", "premises:"]
    usable = 0
    print(f"{rows} cases: {accepted} accepted by host, {refused} refused\n")
    print(f"{'grade':<12}{'catches':>9}{'costs':>7}  where")
    for i, (_, p) in enumerate(prem.sourced):
        where = f"{Path(str(p.get('file'))).name}:{p.get('line')}"
        grade = "unsound" if false[i] else ("empirical" if caught[i] else "inert")
        usable += grade != "unsound"
        print(f"  {grade:<10}{caught[i]:>9}{false[i]:>7}  {where}")
        lines_out += [
            f"  - where: {where}",
            f"    grade: {grade}",
            f"    catches: {caught[i]}",
            f"    costs_witnesses: {false[i]}",
            f"    text: {str(p.get('text', ''))[:150]!r}",
        ]
        if false[i]:
            lines_out.append(f"    first_victim: {victim.get(i, '')!r}")
            lines_out.append("    reason: call-site guard missing from extraction")
    GRADES.write_text("\n".join(lines_out) + "\n", encoding="utf-8")

    sound = sum(caught[i] for i in range(len(prem.sourced)) if not false[i])
    print(f"\n{usable}/{len(prem.sourced)} premises safe to gate on")
    if refused:
        print(f"they catch {sound} of {refused} refusals "
              f"({sound / refused * 100:.1f}%) and cost 0 witnesses")
    print(f"-> {GRADES}")
    return 0


def _refuses(tree, env) -> bool:
    from uo_init.concrete_eval import _refuses as f

    return f(tree, env)


if __name__ == "__main__":
    raise SystemExit(main())
